### ISSUE TITLE
No way to specify whether it's DST.

### ISSUE THREAD

**Issue by obskyr** [sdispater/pendulum#100]
[Just as with Arrow](https://github.com/crsmithdev/arrow/issues/72), there's **no way to specify whether it's DST or not for ambiguous datetimes** - neither through `pendulum.Pendulum`'s constructor nor `pendulum.create`.

For example:
```python
# Are these 02:00 before or after turning the clock back? After, according to Pendulum. Always.
pendulum.Pendulum(2017, 10, 29, 2, 0, tzinfo='Europe/Stockholm')
pendulum.create(2017, 10, 29, 2, 0, tz='Europe/Stockholm')
```

As it stands now, if you want the time on the earlier side of turning the clock back, you have to use an ugly workaround - and one that's not at all viable if you don't *know* whether the time will be ambiguous, at that:

```python
pendulum.create(2017, 10, 29, 2, 0, tz='Europe/Stockholm').subtract(hours=1)
```

Pytz supports specifying this in the tzinfo.localize function via the is_dst parameter - for example, timezone("Europe/Stockholm").localize(datetime(2017, 10, 29, 2, 0), is_dst=True). I propose Pendulum do the same and add an `is_dst` parameter to both `pendulum.Pendulum` and `pendulum.create`, that just as in pytz is only used to resolve ambiguous datetimes.

The default behavior of falling *after* turning the clock back is congruent with pytz, but not with Arrow. No value judgment on what should be done there, just giving you the deets. Maybe an exception should be raised, even (or maybe not, as it'd mean an incredibly rare and hard-to-track-down exception).

**Comment by sdispater** [comment]
I think you missed the [Timezones](https://pendulum.eustace.io/docs/#timezones) section of the documentation.

You can control the normalization behavior:

```python
import pendulum

pendulum.set_transition_rule(pendulum.PRE_TRANSITION)

pendulum.create(2013, 3, 31, 2, 30, 0, 0, 'Europe/Paris')
'2013-03-31T01:30:00+01:00'
pendulum.create(2013, 10, 27, 2, 30, 0, 0, 'Europe/Paris')
'2013-10-27T02:30:00+02:00'

pendulum.set_transition_rule(pendulum.TRANSITION_ERROR)

pendulum.create(2013, 3, 31, 2, 30, 0, 0, 'Europe/Paris')
# NonExistingTime: The datetime 2013-03-31 02:30:00 does not exist
pendulum.create(2013, 10, 27, 2, 30, 0, 0, 'Europe/Paris')
# AmbiguousTime: The datetime 2013-10-27 02:30:00 is ambiguous.
```

**Comment by obskyr** [comment]
Ah, I see. I did miss that part; thank you. `pendulum.set_transition_rule(pendulum.TRANSITION_ERROR)` is a pretty sweet way to handle that.

I'm not sure I'm happy with it always being module-level, though... That's not multithreading-friendly, is it? If you have something like a "DST" checkbox for a user, or you determine based on which side the user is on now... that's also a bit of an API oddity, is it not?

**Comment by sdispater** [comment]
Well, `create()` does not support it but when you instantiate a `Pendulum` instance you can pass the `fold` (the same as the standard librayr) keyword to control the behavior.

```python
from pendulum import Pendulum

# Default behavior
dt = Pendulum(2013, 10, 27, 2, 30, 0, 0, 'Europe/Paris')
dt.isoformat()
'2013-10-27T02:30:00+01:00'

# Pre transition
dt = Pendulum(2013, 10, 27, 2, 30, 0, 0, 'Europe/Paris', fold=0)
dt.isoformat()
'2013-10-27T02:30:00+02:00'

# Post transition
dt = Pendulum(2013, 10, 27, 2, 30, 0, 0, 'Europe/Paris', fold=1)
dt.isoformat()
'2013-10-27T02:30:00+01:00'
```

And the idea behing setting it at module-level is that the case where you want it specific for a call is rare and I wasn"t enclined to bloat the API for such edge cases. And in the case someone wants it they can either use the `fold` attribute or use the timezone library directly.

**Comment by obskyr** [comment]
Ah, sweet! `fold`, huh. I suppose that does pretty much exactly what I asked, hahah. Doesn't let you set the error behavior, and doesn't exist in `create`, but honestly... *whatever*. Thanks!
