### ISSUE TITLE
parser doesn't seem to properly parse exif formatted datetime

### ISSUE THREAD

**Issue by jMyles** [sdispater/pendulum#101]
Hey there.  Thanks for pendulum.

It seems that pendulum.parse() does the wrong thing for strings gleaned by PIL's ExifTags interface.

For example, on a Canon S-series camera, the string for the key 'DateTime" is: 
```'2016:12:26 15:45:28'```

By pendulum parses this into this Pendulum object:
```2017-03-16T11:21:27+00:00```

**Comment by sdispater** [comment]
Well, the thing is the string is not really standard (the `:` separator is mostly reserved for time information) so `pendulum` will fallback on the `dateutil` parser which produces the error:

```python
>>> from dateutil.parser import parse

>>> parse('2016:12:26 15:45:28')
datetime.datetime(2017, 3, 16, 15, 45, 28)
```

To make it work you have to use `from_format()`:

```python
>>> import pendulum

>>> pendulum.from_format('2016:12:26 15:45:28', '%Y:%m:%d %H:%M:%S')
# <Pendulum [2016-12-26T15:45:28+00:00]>
```

**Comment by jMyles** [comment]
Roger.  I agree it's an odd format, but to the degree that `parse()` is generally applicable for datetime representations to be found in the wild: do you think that Exif data from Canon cameras is common enough to warrant special logic?

If so, I can work on a pull request.

**Comment by SethMichaelLarson** [comment]
I'm +1 on this having dealt with EXIF data in the past.

**Comment by emattiza** [comment]
+1 on the issue as well. implemented a unit test for the single case presented above, and a slight modification to the COMMON regex used in the parser for YYYY:MM:DD separators. from_format does look to be the appropriate parse option though fwiw. PR this?

**Comment by sdispater** [comment]
Version `1.2.0` has just been released with this feature included.
