### ISSUE TITLE
Conversion to numpy.datetime64 causes a DeprecationWarning

### ISSUE THREAD

**Issue by nathanielatom** [sdispater/pendulum#104]
Converting a `Pendulum` object to `numpy.datetime64` causes the following warning:

```
import pendulum
import numpy as np
np.__version__ # prints '1.12.1'

np.datetime64(pendulum.now())
# prints:
# .../__main__.py:1: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
# numpy.datetime64('2017-04-13T23:12:04.986766')

np.datetime64(pendulum.now().replace(tzinfo=None))
# also prints
# .../__main__.py:1: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
# numpy.datetime64('2017-04-13T19:18:06.032316')
```

This looks like a very promising library, but I'll probably need better numpy integration before I can use it.

**Comment by sdispater** [comment]
The thing is I made the choice that every Pendulum instance would be aware and that I would not support naive datetimes. And this will not change for versions `1.x`.

However, I might introduce it in version `2.0`. There is no ETA though.

**Comment by nathanielatom** [comment]
Fair enough, that makes sense. Instead of a major overhaul, a simple util function/method could be really handy, something like:

```
def to_np_datetime64(timestamp):
    # convert to UTC (numpy does this when it raises the warning anyway)
    # convert to datetime.datetime
    # strip timezone
    # convert to numpy.datetime64
    return
