### ISSUE TITLE
How to get the timedelta from string like '1d' '1month' '1week'

### ISSUE THREAD

**Issue by ramwin** [sdispater/pendulum#105]
I'm writing the config file, there is a configuration item named `cache_expire`. I want to enable users to set it to `300(default in seconds)`, or `1day`, `1d`, `1week` .etc. instead of calculating how many seconds are there in a week. How can I use pendulum to parse the string?

**Comment by sdispater** [comment]
You can't directly get an interval from strings like `1day`, `1week`. You will have to parse these strings yourself into a format compatible with Pendulum.

**Comment by jneines** [comment]
I am using the humanfriendly package for this. `humanfriendly.parse_timespan` is able to parse these things and returns the timespan in seconds as a floating point number. 

E.g.
```
import humanfriendly

print(humanfriendly.parse_timespan('1day')
>>> 86400.0
print(humanfriendly.parse_timespan('1week')
>>> 604800.0
```
