### ISSUE TITLE
docs should mention tzinfo='local'

### ISSUE THREAD

**Issue by bukzor** [sdispater/pendulum#106]
I suspected this was the case, coming from arrow, but I had to dig into the code to find it.
Given a tzinfo of string "local", the local timezone is used, when constructing a Pendulum.

**Comment by sdispater** [comment]
Thanks for reporting. I can't believe I forgot to mention this in the documentation.

I will update the documentation by adding a section covering this.

**Comment by sdispater** [comment]
There is now a note in the [Instantiation](https://pendulum.eustace.io/docs/#instantiation) section mentioning that the `local` string is supported.
