### ISSUE TITLE
docs have incorrect example output

### ISSUE THREAD

**Issue by bukzor** [sdispater/pendulum#107]
[This page](https://pendulum.eustace.io/faq/) shows pendulum giving nonsense output, but in fact it does the right thing:

```
>>> pendulum.parse('20160413')
<Pendulum [2016-04-13T00:00:00+00:00]>
```

**Comment by bukzor** [comment]
😄

**Comment by sdispater** [comment]
This is fixed on the FAQ. Thanks for reporting this.
