### ISSUE TITLE
3.6+ compatible only

### ISSUE THREAD

**Issue by sdispater** [sdispater/pendulum#110]

**Comment by obskyr** [comment]
What is this about? Dropping support for Python 3.5 already?

**Comment by sdispater** [comment]
Python 2.7 and 3.2+ will still be supported in the `1.x` versions for which I don't plan on dropping support anytime soon.

`2.x` and `1.x` will both coexist and be supported.

**Comment by movermeyer** [comment]
It seems that this never happened and pendulum 2.x supports Python 2.7 and 3.4+.
