### ISSUE TITLE
Add support for alternative formatting in from_format

### ISSUE THREAD

**Issue by dusktreader** [sdispater/pendulum#116]
You can set the formatter for pendulum to use the 'alternative' format, but there is no way that I can see to actually use 'alternative' formatting when parsing a string. This is definitely needed in the case where an application records a timestamp as a string using 'alternative' format and then needs to extract that same timestamp later.

**Comment by sdispater** [comment]
This will be the case in the next major version (`2.0`). In fact, this will be the only formatting supported in `from_format()`.

However, I might backport it to `1.x` versions as an opt-in option to ease the transition.
