### ISSUE TITLE
How does one 'get at' custom directive %_z?

### ISSUE THREAD

**Issue by WDBell** [sdispater/pendulum#122]
The documentation points to use of method `.strftime` in the `time` module but I can't find it in pendulum.

**Comment by sdispater** [comment]
I am not sure I understand.

`strftime()` is available on `Pendulum`, `Date` and `Time` objects.

```python
>>> import pendulum
>>> dt = pendulum.create(2017, 6, 14, 12, 34, 56, tz='Europe/Paris')
>>> dt.strftime('%Y-%m-%dT%H:%M:%S%_z')
'2017-06-14T12:34:56+02:00'
```

**Comment by WDBell** [comment]
Thanks for responding, and for your patience. I'm looking at a 2015 question on StackOverflow where someone wonders why he gets 'Eastern Daylight Time' for `time.strftime('%z')` on a Windows machine. (This bug persists through to Win10, as you almost certainly know.) The question was answered but I was hoping to suggest a strict parallel using pendulum. To quote the SO question, how can one get 'the UTC offset in the form +HHMM or -HHMM'?

**Comment by sdispater** [comment]
You have two choices:

```python
>>> pendulum.now().strftime('%z')
'-0400'
>>> pendulum.now().format('Z', formatter='alternative')
'-0400'
```

**Comment by WDBell** [comment]
Thank you, I'll pass it on.
