### ISSUE TITLE
Pendulum 1.2.2 C compiler warning(s)

### ISSUE THREAD

**Issue by davidghiurco** [sdispater/pendulum#127]
When installing pendulum on my company's build server, I get the following c compiler warning(s):

Searching for pendulum>=1.2.1
Reading https://pypi.python.org/simple/pendulum/
Downloading https://pypi.python.org/packages/98/b8/225ce8d0e1aaae0edd35d6e63bbd446b5663dad43fe6d01b786c1e6c07e2/pendulum-1.2.2.tar.gz#md5=4a87fa6ac7dc900d6935a46f21414776
Best match: pendulum 1.2.2
Processing pendulum-1.2.2.tar.gz
Writing /tmp/easy_install-j0cqVp/pendulum-1.2.2/setup.cfg
Running pendulum-1.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-j0cqVp/pendulum-1.2.2/egg-dist-tmp-KBd4Ph
warning: no previously-included files matching '*' found under directory 'tests'
warning: no previously-included files matching '*' found under directory 'benchmark'
pendulum/_extensions/_helpers.c: In function ‘parse_iso8601’:
pendulum/_extensions/_helpers.c:429:9: warning: variable ‘has_hour’ set but not used [-Wunused-but-set-variable]
     int has_hour = 0;
         ^
zip_safe flag not set; analyzing archive contents...

Just a heads up. It's definitely not a big issue, but you might want to clean up some code =)

**Comment by sdispater** [comment]
Thanks for reporting this.

For some reason the warning is not triggered on my machine when building extensions.

Anyway, it should be fixed in commit 6851fe485b761f1792bbb1aa0cf5de367fa2f5df

It will land in the next bugfix release.

**Comment by sdispater** [comment]
Version `1.2.3` is out!
