### ISSUE TITLE
Improve parsing with new features (strictness, multiple formats, natural language, alternative format)

### ISSUE THREAD

**Issue by Delgan** [sdispater/pendulum#132]
Hello.

I would like to extend pendulum functionalities in terms of parsing. Many of these features are not implemented in any of the "competing" libraries (Arrow, Maya, Dolerean), would they have their place in Pendulum?

Here is what has been going on in my mind for some time:

---

### Add an optional flag `strict` to function `from_format()`
Related to this kind of issue: [datetime - how to require 2-digit days and months?](https://stackoverflow.com/questions/44731156/datetime-how-to-require-2-digit-days-and-months#comment76445103_44731156)
Today, the only way to strictly parse a formatted date string is to make use of a regex.
This would be nice if Pendulum could solve the problem.
[Moment.js](https://momentjs.com/docs/#/parsing/string-formats/) handles this easily, for example:
```javascript
moment('2012-5-14', 'YYYY-MM-DD').isValid();  // true
moment('2012-5-14', 'YYYY-MM-DD', true).isValid();  // false
```

---

### Accept multiple formats in function `from_format()`
Once again, this is stolen from [Moment.js](https://momentjs.com/docs/#/parsing/string-formats/) but this feature could be very usefull is some cases.
This would allow to write something like this without raising a `ValueError`:
```python
pendulum.from_format('1975-13-01', ['%Y-%m-%d', '%Y-%d%m'])
```

---

### Implement extended natural language parsing to the `parse()` function
For me, it seems a bit weird that `pendulum.parse('now')` works while `pendulum.parse('tomorrow')` raises an error.
Also, parsing relative and humanized dates like `5 days ago` would be huge.
Using [dateparser](https://github.com/scrapinghub/dateparser) maybe?

---

### It should be possible to use alternative format for parsing
This is basically https://github.com/sdispater/pendulum/issues/116.

---

### Simplify the API by unifying `from_format` and `parse`
Just one last idea: would not it be possible to add a `format` argument to `parse()` so it works in a similar to `from_format()`? Since `parse()` will by default find the format that best fits, it does not seem illogical to have an argument to restrict the desired format(s).

---

I am aware that this will require a lot of work, since it probably imply a replacement of `datetime.strptime()` which is used in the background.

However, if you find some of these ideas interesting, I will be happy to contribute to Pendulum and work on the implementation of these new features. :)

**Comment by sdispater** [comment]
Thanks for your interest in `pendulum`!

I will try to address each point you made.

### Add an optional flag strict to function from_format()

`from_format()` will actually use the alternative tokens (like `YYYY`, `MM`, `DD`) in the next major version (`2.0`). At first, it will be strict only and I don't plan on supporting  `strict` keyword.

### Accept multiple formats in function from_format()

Once I change the `from_format()` to accept the new tokens that's something I could add. However, I don't think I will add it in the `2.0` version but rather in one of the subsequent minor versions.

### Implement extended natural language parsing to the parse() function

That's not something I plan on supporting. I know that's something people like but I am not sure that's where I want the `parser` to go. It will even be stricter in `2.0` by default. And if you really want it it's as simple as:

```python
>>> import pendulum
>>> import dateparser
>>> parsed = dateparser.parse('Fri, 12 Dec 2014 10:55:50')
>>> pendulum.instance(parsed)
```

### It should be possible to use alternative format for parsing

See above. The alternative tokens will be used in `from_format()` in the `2.0` version.

### Simplify the API by unifying from_format and parse

I am not sure about this. They have different purposes and I don't want make `parse()` more complex.

Anyway, thanks for your input :-)

**Comment by Delgan** [comment]
Thank you for the answer.

The future `from_format()` looks great!

Indeed, I realized that `dateparser` actually implemented many of what I described.
It would have been nice to be able to use Pendulum as the "all-in-one" library when dealing with dates in any way. But I suppose one more import is not so bad. :)

**Comment by AlJohri** [comment]
@sdispater I would also like to see from_format accept multiple formats. For example I need to parse `MMMM` or `MMM`
