### ISSUE TITLE
Cannot figure out how to use timezones correctly

### ISSUE THREAD

**Issue by Phxntxm** [sdispater/pendulum#135]
Just for an example, if I want to get the timezone in Moscow, I'm trying to use `pendulum.timezone` and have tried:
MSK
UTC + 3
+3
Moscow
Russia/Moscow

None of these work...I do not understand what is required and what is accepted. UTC works, so you'd think MSK would since that's the abbreviation...

**Comment by sdispater** [comment]
The timezone for Moscow is `Europe/Moscow` and `MSK` is not a valid time zone.

Internally, `pendulum` uses the [IANA time zone database](https://www.iana.org/time-zones).

**Comment by Phxntxm** [comment]
Thank you that link was essentially what I was looking for.

Just FYI though MSK is most certainly a valid time zone
https://www.timeanddate.com/worldclock/russia/moscow

`CDT`, `CST`, nor `CEST` work either...and I know for a fact these are valid timezones, I live in CST timezone.
