### ISSUE TITLE
now() method (or similar) raises IOError when called with an empty string.

### ISSUE THREAD

**Issue by luis181** [sdispater/pendulum#141]
If the `now()`, `today()`, `tomorrow()`, etc., methods are called with an empty string, an `IOError` is raised, which is counter intuitive. Maybe raising a `ValueError` is more appropriate, like when the timezone is not found. Might be by design: the user only has to be sure the string is not empty. Maybe it slipped.

**Comment by sdispater** [comment]
Yes, it should return a `ValueError` in the case of an empty string.

However, it's not a problem in pendulum but rather in [pytzdata](https://github.com/sdispater/pytzdata) that fails to detect an empty string as an invalid value.

I will fix it there and you will only need to update the `pytzdata` package

**Comment by sdispater** [comment]
It's now fixed in `pytzdata` so you can update it to the latest version.
