### ISSUE TITLE
How do you get a list of accepted timezones?

### ISSUE THREAD

**Issue by graingerkid** [sdispater/pendulum#143]
Is there a way to list all accepted timezones?

I've looked at https://www.iana.org/time-zones and I can't even find the list... seems like it should be accessible via Pendulum?

**Comment by sdispater** [comment]
You are right. At this time, there is no easy way to get the available timezones.

This issue has come up before so I will see if I can provide  a way to make this accessible.

**Comment by sdispater** [comment]
There is now a `timezones` property to get all timezones available (see https://pendulum.eustace.io/blog/pendulum-1-3-0-is-out.html)
