### ISSUE TITLE
How to convert a iso timestamp_tz to unix timestamp and viceversa? Can't find on documentation

### ISSUE THREAD

**Issue by carlosviansi** [sdispater/pendulum#149]
I have been trying to move from `Arrow` to `Pendulum` given the raised concerns and the fact `Arrow` appears to no longer be maintained, but I can't seem to figure out (or find online or docs) how to do this simple operation from `Arrow` in `Pendulum`:

```
import arrow
iso_start_datetimez = '2017-09-13T15:19:00-10'
iso_end_datetimez = '2017-09-13T15:19:00-09'

start_timestamp = arrow.get(iso_start_datetimez).timestamp
end_timestamp = arrow.get(iso_end_datetimez).timestamp

print(start_timestamp)
print(end_timestamp)
print(start_timestamp - end_timestamp)
```

Output:

```
1505351940
1505348340
3600
```
Which outputs correctly, as it differs by 1 hour, as expected. The questions that follow from this in trying to reproduce in `Pendulum`:

- The documentation suggests to create a timestamp object within Pendulum:

```
pendulum.from_format(time, format, tz)
```

Where all `tz` examples I have found follow the format: `'Europe/London'`. 

1) The following must be used, however, it is easier to find online the time zone relative to GMT than the exact word used for the variable `tz`. (I am hosted in Hawaii for example). Is there a way I can pass as input an iso(?) format string? `'2017-09-13T15:19:00-10'` as arrow takes? This is even truer due to #143.

2) How to convert to a unix timestamp? The only reference to the word unix timestamp in the documentation is as follows:

```
The final create function is for working with unix timestamps. from_timestamp() will create a Pendulum instance equal to the given timestamp and will set the timezone as well or default it to UTC.
```

A code example would be greatly appreciated, as the one I provided above in `Arrow`.

3) How to convert back from unix timestamp to a pendulum object?

I can't find an example of the documentation for this. 

I tried leveraging the fact that `pendulum` inherit `datetime` but with the whole `naive timestamp` datetime hell, for some reason it is not working. 

Lastly, thank you for maintaining this project. Coming from R and `lubridate`, I never thought using time zones in Python base and with Python 3 would be so problematic.

**Comment by sdispater** [comment]
Thanks for your interest in `pendulum`.

You have to use the `parse()` function to get `pendulum` objects from both your strings.

```python
>>> import pendulum

>>> iso_start_datetimez = '2017-09-13T15:19:00-10'
>>> iso_end_datetimez = '2017-09-13T15:19:00-09'

>>> start = pendulum.parse(iso_start_datetimez)
>>> end = pendulum.parse(iso_end_datetimez)
```

At this point, you have several options to get the unix timestamp (see https://pendulum.eustace.io/docs/#attributes-and-properties):

```python
>>> start.timestamp()
1505351940.0
>>> start.int_timestamp
1505351940
>>> start.float_timestamp
1505351940.0
```

Regarding #143, the next release will introduce a new `timezones` properties which will return the available timezones:

```python
import pendulum

pendulum.timezones
('CET',
 'CST6CDT',
 'Cuba',
 'EET',
 'Egypt',
 'Eire',
 ...,
 'US/Michigan',
 'US/Mountain',
 'US/Pacific',
 'US/Pacific-New',
 'US/Samoa')
```

> How to convert back from unix timestamp to a pendulum object?

This is what the `from_timestamp()` function is for:

```python
>>> import pendulum
>>> pendulum.from_timestamp(1505351940)
<Pendulum [2017-09-14T01:19:00+00:00]>
>>> pendulum.from_timestamp(1505351940, tz=-10)
<Pendulum [2017-09-13T15:19:00-10:00]>
```

**Comment by carlosviansi** [comment]
@sdispater Thank you for putting the time to guide me in the right direction in getting started in pendulum! Very much appreciated! :-) Looking forward using it on all my projects from now on!
