### ISSUE TITLE
Naive datetimes?

### ISSUE THREAD

**Issue by dagraham** [sdispater/pendulum#150]
Is it possible to create a naive datetime in pendulum, i.e., one without a timezone? I need them for what some applications call "floating" events. E.g., a reminder to take meds at 10am and 4pm in whatever timezone one happens to be.

**Comment by sdispater** [comment]
At the time, no. The initial choice was that all datetimes would be timezone aware.

However, I am thinking about introducing a `naive()` method to `Pendulum` instances to provide this feature.

**Comment by dagraham** [comment]
Sebastian,

Thanks for your reply and for pendulum. I would normally test for naive by checking whether or not tzinfo is None. It turns out that there is a supported timezone called ‘Factory’ with a zero offset and an abbrev ‘-00’. I can just treat any pendulum object with this timezone as naive and that works perfectly for me.

If I could make a feature request it would be to add a token ‘a’ that would give lower case ‘am' and ‘pm’ or, better still, ‘a’ and ‘p’.

Thanks,
Dan



On October 5, 2017 at 4:56:49 AM, Sébastien Eustace (notifications@github.com<mailto:notifications@github.com>) wrote:

At the time, no. The initial choice was that all datetimes would be timezone aware.

However, I am thinking about introducing a naive() method to Pendulum instances to provide this feature.

**Comment by bolkedebruin** [comment]
A naive() function would definitely be appreciated or allow to set "tzinfo=None" and not initialize it with UTC. I work with croniter and I need to convert to naive date times in order to have croniter respect exact times (e.g. ignore DST). At the moment it seems I need to create a hack (override private properties) to make this work.

**Comment by odinho** [comment]
This seems to have been implemented. Could you close this issue?

```
>>> pendulum.parse('2017-08-12T02:52:00Z').in_timezone('Europe/Oslo').naive()
DateTime(2017, 8, 12, 4, 52, 0)
```
