### ISSUE TITLE
Support for sqlalchemy-utils?

### ISSUE THREAD

**Issue by danqing** [sdispater/pendulum#155]
SQLAlchemy is pretty much the de facto standard for Python ORMs, and there's the [SQLAlchemy-Utils](https://github.com/kvesteri/sqlalchemy-utils) that provides convenience types, like Arrow.

Maybe Pendulum can also consider adding itself there - this way it can play nicer with databases.

**Comment by edgarrmondragon** [comment]
I think this can be closed: https://github.com/kvesteri/sqlalchemy-utils/blob/db32722aeb7439778cea9473fe00cddca6d2e302/sqlalchemy_utils/types/enriched_datetime/pendulum_datetime.py#L12-L17
