### ISSUE TITLE
wrong date time under pypy3 for Asia/Shanghai

### ISSUE THREAD

**Issue by honglet** [sdispater/pendulum#163]
In the year of 1990 and 1991, China used daylight saving time. This seems to be handled well by pendulum under python3, but not under pypy3. Please see the following example and the bold italic lines are the errors:

import pytz
from datetime import datetime
import pendulum

tz2 = pytz.timezone("Asia/Shanghai")
tz = pendulum.timezone("Asia/Shanghai")
x="1991-04-20 01:49:08"
print("pytz test1:", tz2.localize(datetime.strptime(x, "%Y-%m-%d %H:%M:%S")).timestamp())
print("pendumlum test:", datetime.strptime(x, "%Y-%m-%d %H:%M:%S").replace(tzinfo=tz).timestamp())
x="1992-04-20 01:49:08"
print("pytz test1:", tz2.localize(datetime.strptime(x, "%Y-%m-%d %H:%M:%S")).timestamp())
print("pendumlum test:", datetime.strptime(x, "%Y-%m-%d %H:%M:%S").replace(tzinfo=tz).timestamp())

results:
python3 test.py 
pytz test1: 672079748.0
pendumlum test: 672079748.0
pytz test1: 703705748.0
pendumlum test: 703705748.0

pypy3 test.py 
**_pytz test1: 672079748.0
pendumlum test: 672083348.0_**
pytz test1: 703705748.0
pendumlum test: 703705748.0

**Comment by sdispater** [comment]
Thanks for reporting this!

I will take a look and get back to you.

**Comment by sdispater** [comment]
This is fixed in commit 5a596b0

It will land in the next bugfix release :-)

**Comment by sdispater** [comment]
This should be fixed in the latest `1.4.1` release :-)
