### ISSUE TITLE
Naive datetimes

### ISSUE THREAD

**Issue by sdispater** [sdispater/pendulum#166]
We should be able to create naive datetimes if we really need them. However, they should not be the default.

The best approach would be to allow creation in the two following ways:

```
>>> import pendulum
>>> pendulum.datetime(2017, 12, 3, 1, 2, 3)
>>> now = pendulum.now()
>>> now.naive()
```

**Comment by rlittlefield** [comment]
Would the naive datetime be generated using the naive version of the pendulum object's existing timezone? Or would UTC be the only way to get one out? I could also see having an optional/required tz parameter to the `naive` function.

**Comment by sdispater** [comment]
The `naive()` method will just remove the timezone information, regardless of what it is:

```python
>>> import pendulum
>>> dt = pendulum.datetime(2018, 3, 26, 12, 34, tz='Europe/Paris')
>>> print(dt)
'2018-03-26T12:34:00+02:00'
>>> naive = dt.naive()
>>> print(naive)
'2018-03-26T12:34:00'
```

**Comment by sdispater** [comment]
Closing since it's now available.
