### ISSUE TITLE
Default timezone isn't utc?

### ISSUE THREAD

**Issue by leafonsword** [sdispater/pendulum#171]
From [FAQ](https://pendulum.eustace.io/faq/). 
`It also removes the notion of naive datetimes: each Pendulum instance is timezone-aware and by default in UTC for ease of use.`
But from my test, seems dfault timezone is local machine's timezone, my machine's time zone is 'Asia/Shanghai'
```
>>> pendulum.now()                                                                                                                                               
<Pendulum [2018-01-05T15:51:55.975424+08:00]>       
                                                                                                             
>>> pendulum.now('Asia/Shanghai')                                                                                                                                
<Pendulum [2018-01-05T15:52:02.086741+08:00]>      
                                                                                                              
>>> pendulum.now().in_timezone('UTC')                                                                                                                            
<Pendulum [2018-01-05T07:52:27.614535+00:00]>                                                                                                                    
>>>                                                                                                                
```
So now() has same result like now('Asia/Shanghai'), not utc

**Comment by SethMichaelLarson** [comment]
Can confirm in the code that `Pendulum.now()` uses `datetime.datetime.now()` not `datetime.datetime.utcnow()`.

**Comment by pganssle** [comment]
@SethMichaelLarson I would certainly hope it doesn't use `datetime.datetime.utcnow()`. Even if you want a datetime in `UTC` you shouldn't use `utcnow`, you should use `datetime.datetime.now(UTC)` instead.

**Comment by SethMichaelLarson** [comment]
Could you explain the difference between the two?
Pendulum uses `datetime.datetime.utcnow().replace(tzinfo=UTC)` for the UTC case.

**Comment by pganssle** [comment]
I will make a PR soon to remove the use of `utcnow` from Pendulum's internals, as it is pointless. You can see my comment [here](https://github.com/crsmithdev/arrow/pull/486#issuecomment-349951436) which explains why `utcnow` is a pointless aberration.

**Comment by SethMichaelLarson** [comment]
Thanks for the clarification. I'd just say that a lot of us are here to learn and that programming with dates and times (even without timezones!) is really difficult, even for people who have a good control of the language.

**Comment by pganssle** [comment]
Looking at pendulum's interface more carefully, it seems like `pendulum` interprets naive `datetime`s as representing UTC, though Python assumes that they represent local time whenever a naive datetime is generated from some timezone-aware(ish) source, such as `datetime.now`, or when using `datetime.astimezone`. I think both choices are defensible, though the fact that they are different but intended to inter-operate probably causes some confusion.

@leafonsword I'm guessing that the reason that `pendulum.now()` defaults to your local time is twofold:

1. `pendulum` is trying to be a more-or-less drop-in replacement for `datetime`, and `datetime.now()` (with no arguments) provides a naive datetime in local time.
2. `pendulum.utcnow()` can be used to get a datetime in UTC (and, unlike `datetime.utcnow()`, the datetime is not naive, assuaging my main problem with `utcnow`).

**Comment by leafonsword** [comment]
@pganssle Thx for your explaination~
