### ISSUE TITLE
Incorrect handling of time differences with timezones in version 1.4.2 

### ISSUE THREAD

**Issue by ssuerbier** [sdispater/pendulum#183]
Under version 1.4.1 the following tests pass, under 1.4.2 only the one without timezones does.

`tests/period_tests/test_add_subtract.py`
```
def test_period_over_midnight_no_tz():
    start = pendulum.create(2018, 2, 25, 23, 0)
    end = start.add(hours=1)
    period = end - start
    new_end = start + period

    assert new_end == end

def test_period_over_midnight_tz():
    start = pendulum.create(2018, 2, 25, tz='Europe/Paris')
    end = start.add(hours=1)
    period = end - start
    new_end = start + period

    assert new_end == end
```

The change that introduced this behavior is here: https://github.com/sdispater/pendulum/commit/5b06241f07ade260cb8825e7394890f2e4937b9c#diff-33c1eb0997d2cda44f837c4ede470d7cR200

**Comment by sdispater** [comment]
Commit 9b3a086 fixes the issue.

It will land in the next bugfix release.

**Comment by ssuerbier** [comment]
That was quick, thank you!
