### ISSUE TITLE
Installation error: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

### ISSUE THREAD

**Issue by rominf** [sdispater/pendulum#187]
I'm trying to install `pendulum` on openSUSE 42.3 (Python 3.4.6). I have following error:
```
pip install --user pendulum
Collecting pendulum
  Using cached pendulum-1.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in pendulum setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in python-dateutil (>=2.6.0.0,<3.0.0.0) at  (>=2.6.0.0,<3.0.0.0)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gadrpgag/pendulum/
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by sdispater** [comment]
It seems that older version of distutils do not support this requirement format.

I will change it and make a new release.

**Comment by sdispater** [comment]
I just tested and I can't reproduce this error both on MacOS and Ubuntu. So it may be caused by an old setuptools version that comes in openSUSE 42.3.

You might want to upgrade `setuptools` (`pip install setuptools -U`) for now while I try to figure out a way to be compatible with older versions.

I will also build wheels  for Python 3.4 from now on.

**Comment by 7yl4r** [comment]
I ran into this and resolved it by upgrading setuptools as suggested from `setuptools-19.2` to `setuptools-39.1.0`, thanks.

**Comment by liyao2598330** [comment]
> 
> 
> I just tested and I can't reproduce this error both on MacOS and Ubuntu. So it may be caused by an old setuptools version that comes in openSUSE 42.3.
> 
> You might want to upgrade `setuptools` (`pip install setuptools -U`) for now while I try to figure out a way to be compatible with older versions.
> 
> I will also build wheels for Python 3.4 from now on.

Thanks,it works

**Comment by hyBio** [comment]
nice
