### ISSUE TITLE
Add precision option to to_datetime_string()

### ISSUE THREAD

**Issue by leafonsword** [sdispater/pendulum#191]
to_datetime_string()'s result just to second precision:
```
>>> dt = pendulum.now()
>>> dt.to_datetime_string()
'2018-04-11 15:44:44'
```

Could to_datetime_string() add a option letting user choosing other precison such as millisecond、micosecond? While default precisipn still to be second ~

**Comment by sdispater** [comment]
The `to_xxx_string()` methods are supposed to be simple and with a predictable behavior and thus do not accept options. So unfortunately, I won't be adding a precision option for it.

If you want a more customizable behavior you can use `format()`.
