### ISSUE TITLE
UTC indicator should be Z not +00:00 in ISO8601 strings

### ISSUE THREAD

**Issue by finetuned89** [sdispater/pendulum#192]
From the ISO 8601 specification:

> The zone designator is empty if use is made of local time in accordance with 4.2.2.2 through 4.2.2.4, it is the UTC designator [Z] if use is made of UTC of day in accordance with 4.2.4 and it is the difference-component if use is made of local time and the difference from UTC in accordance with 4.2.5.2.

From this text, I infer that you are not supposed to use "+00:00" to indicate UTC time.

Pendulum should use the Z indicator instead of +00:00:

```
>>> pendulum.utcnow().to_iso8601_string()
'2018-04-17T11:30:08+00:00'
```

**Comment by Delgan** [comment]
Note that this is fixed in v2: fc33b9f7090d83be4ce82551fb0ae4124afed982
