### ISSUE TITLE
Documentation for set() method and timezone is wrong

### ISSUE THREAD

**Issue by dusktreader** [sdispater/pendulum#194]
The documentation says:

After getting the deprecaton warning about the `timezone_` method, I tried to change to using `set`. Following the documentation ends up with this error:
 
`replace() got an unexpected keyword argument 'tz'`

Digging into the source-code reveals that the actual keyword argument for the `set()` and `replace()` method should be `tzinfo`

**Comment by sdispater** [comment]
Actually, this is an oversight on my part since `tz` should be accepted but not `tzinfo`.

I will fix it an make a bugfix release.

**Comment by dusktreader** [comment]
In the meantime, what's the correct work-around?

**Comment by sdispater** [comment]
I just pushed a new bugfix release (1.5.1) fixing this issue.
