### ISSUE TITLE
Cleanup API

### ISSUE THREAD

**Issue by sdispater** [sdispater/pendulum#2]
- [x] Remove unnecessary methods (`add_xxx()`, `sub_xxx()`)
- [x] Rename ambiguous methods (`diff_for_humans()` for instance)

**Comment by seemethere** [comment]
Would you rather do these through `**kwargs` similar to how relativedelta does it?

**Comment by sdispater** [comment]
Yes. The `Pendulum` class already has a `add()` method that works like this. The intention here is just to remove the overhead of the various `add_xxx` methods.

**Comment by seemethere** [comment]
Alright I'll put up a PR to do just this.

**Comment by sdispater** [comment]
Thanks.
