### ISSUE TITLE
parse('February 21, 1994') fails for 2.0.0

### ISSUE THREAD

**Issue by timofurrer** [sdispater/pendulum#205]
We at [maya](https://github.com/kennethreitz/maya) have some test doing things like:

```python
pendulum.parse('February 21, 1994')
```
This works fine for releases prior to 2.0.0 but fails for 2.0.0 with the following traceback:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tuxtimo/work/maya/env/lib/python3.6/site-packages/pendulum/parser.py", line 20, in parse
    return _parse(text, **options)
  File "/home/tuxtimo/work/maya/env/lib/python3.6/site-packages/pendulum/parser.py", line 36, in _parse
    parsed = base_parse(text, **options)
  File "/home/tuxtimo/work/maya/env/lib/python3.6/site-packages/pendulum/parsing/__init__.py", line 64, in parse
    return _normalize(_parse(text, **_options), **_options)
  File "/home/tuxtimo/work/maya/env/lib/python3.6/site-packages/pendulum/parsing/__init__.py", line 116, in _parse
    raise ParserError('Unable to parse string [{}]'.format(text))
pendulum.parsing.exceptions.ParserError: Unable to parse string [February 21, 1994]
```

What's going on here? Is this format not supported any more?

**Comment by ViktorHaag** [comment]
This appears to be because `pendulum.parse()` now uses the `strict` option as default-to-True which prevents it from falling back on the dateutil parser for parsing the input string.

**Comment by sdispater** [comment]
@timofurrer The API has changed slightly in the new `2.0` release. The parser is now strict by default (i.e.  it only parses ISO 8601 strings and some common ones). If you want to retrieve the previous behavior you have to pass `strict=False` to `parse()`

**Comment by ViktorHaag** [comment]
@timofurrer I've also determined that, from maya's point of view, the parser now returns things that are not just datetimes (also intervals, durations?), and there seems a pervasive assumption inside maya that pendulum's parser returns only datetimes.

**Comment by timofurrer** [comment]
@sdispater Alright, thanks for the hint. I'll try that

@ViktorHaag That's definitely something we need to have a look at. But how is that not a functional change in the pandulum parser API? Seems like one :)

**Comment by ViktorHaag** [comment]
@timofurrer I don't know if it every promised that pendulum.parse was a public API, or that it would always return something you could treat like a datetime, or whether you inferred that based on its availability and behaviour... but _in any case_, the switch in version from 1.5.x to 2.x pretty clearly indicates that this might be a not-backwards-compatible boundary, so ... 

I don't want to start up a dispute here about "what's a major change and what isn't" or "what's an API and what isn't"... I was just trying to point out that there was more than just strict parsing that would cause issues with Maya's use of this library.

**Comment by timofurrer** [comment]
Okay, that's fine. I wasn't aware that it's not a *public* API :)
We definitely have to check how the functionalities we use, behave in pendulum 2.x and see how we can integrate those.

In any case, thanks for the hint.  :beers:

**Comment by timofurrer** [comment]
I'm going to close this for now.

Thanks guys :beers:
