### ISSUE TITLE
Incorrect formatting inside of f-string

### ISSUE THREAD

**Issue by Cykooz** [sdispater/pendulum#212]
datetime:

```python
>>> import datetime
>>> now = datetime.datetime.now()
>>> f'{now:%H:%M %d.%m.%Y}'
'15:39 16.05.2018'
```

pendulum 2.0.1:

```python
>>> import pendulum
>>> now = pendulum.now()
>>> f'{now:%H:%M %d.%m.%Y}'
'%15:%5 %3.%39.%2018'
```

**Comment by Delgan** [comment]
This is not related to f-string particularly , but rather to `DateTime` formatting in general. 

Since v2, Pendulum only supports **one** type of formatting tokens (previously refered as "alternative formatter" in v1) which is much more intuitive: https://pendulum.eustace.io/docs/#formatter

```python
>>> import pendulum
>>> now = pendulum.now()
>>> f'{now:HH:mm DD.MM.YYYY}'
'21:35 17.05.2018'
```

**Comment by Cykooz** [comment]
In this case the new version of pendulum can't be used as transparent replacement for datetime. I need to find other library to work with time. Because I can not guaranty what type of value will be passed into my code - pendulum.DateTime or datetime.datetime

**Comment by Delgan** [comment]
Fair point.

Can you convert the dates passed to your code?

```python
if not isinstance(dt, DateTime):
    dt = pendulum.instance(dt)
```

**Comment by Cykooz** [comment]
May be...

But what I will do when I need to send DateTime into third-party code, which works with datetime only?

I'm not ready to control which type of time to use all the time.

**Comment by Delgan** [comment]
Except for formatting with a specified format, Pendulum should work transparently with any third-party module as `DateTime` inherits from `datetime`.

If this is still an issue, can you convert the dates to you own subclass, which inherits from `DateTime` while preserving `datetime` formatting?

```python
from pendulum import DateTime
from datetime import datetime

class LegacyDateTime(DateTime):
    __format__ = datetime.__format__

now = LegacyDateTime(2018, 5, 16, 15, 39)

print(f'{now:%H:%M %d.%m.%Y}')
# => 15:39 16.05.2018
```

Note that there is some issues with `DateTime` inheritance in v2 (hopefully soon to be fixed), but I am asking in principle, to know if this solution may solve your issue.

**Comment by sdispater** [comment]
I think the native formatting (via f-strings or `format()`) must be supported since the promise of Pendulum is that it provides drop in type replacements for the standard library.

I will change it.

**Comment by sdispater** [comment]
This should be fixed in the latest release: `2.0.2`

**Comment by dongli** [comment]
It seems this problem is not fixed in `2.0.2`:

```
$ pip3 install pendulum
Collecting pendulum
  Using cached https://files.pythonhosted.org/packages/b1/cb/56de72fc5ea6dc9089ccb673d37c18d98c151004675e273da46ab89a4378/pendulum-2.0.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting python-dateutil<3.0,>=2.6 (from pendulum)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pytzdata>=2018.3 (from pendulum)
  Using cached https://files.pythonhosted.org/packages/2b/b8/a007eedc118838b27247da7c31f25c2b9e68e68ed2ffafed3d340d379e84/pytzdata-2018.5-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0,>=2.6->pendulum)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, pytzdata, pendulum
Successfully installed pendulum-2.0.2 python-dateutil-2.7.3 pytzdata-2018.5 six-1.11.0
$ ipython
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pendulum

In [2]: pendulum.__version__
Out[2]: '2.0.2'

In [3]: pendulum.now().format('%Y%m%d')
Out[3]: '%2018%55%0'
```

**Comment by sdispater** [comment]
@dongli `DateTime.format()` only supports the pendulum formatter tokens (see https://pendulum.eustace.io/docs/#formatter).

This issue is about using the `format()` method on a string to format a `DateTime` instance.

```python
>>> import pendulum
>>> "{:%Y%m%d}".format(pendulum.now())
'20180603'
```

**Comment by dongli** [comment]
@sdispater This changes breaks my codes. 😢

**Comment by sdispater** [comment]
@dongli You can still use this format by using `strftime()`

**Comment by dongli** [comment]
@sdispater That will still cause massive changes in the codes.
