### ISSUE TITLE
pendulum.replace does not correctly set tzinfo

### ISSUE THREAD

**Issue by hoesler** [sdispater/pendulum#214]
Using pendulum 1.5.1, I get an `IndexError: list index out of range` exception using the following code

```python
import croniter
import pendulum
import datetime
croniter.croniter('0 0 * * *', pendulum.today(tz=pendulum.UTC)).get_next(datetime.datetime)
```

After some debugging, I think the following line in the `replace` method is causing the error:
https://github.com/sdispater/pendulum/blob/41f5ac3c145b66dbf5c2f1d9c6860a8c776a09f2/pendulum/pendulum.py#L2132

Replacing `tzinfo = self._tzinfo.tz` with `tzinfo = self._tzinfo` fixes it.

**Comment by Delgan** [comment]
Note that this is fixed in v2, if you are able to update Pendulum.
