### ISSUE TITLE
timedelta bug

### ISSUE THREAD

**Issue by Benjamin-Setzer** [sdispater/pendulum#220]
now = datetime.datetime.now()
now + (datetime.datetime(2018, 1, 1) - now)
-> datetime.datetime(2018, 1, 1, 0, 0)

but:
pnow = pendulum.now()
pnow + (pendulum.datetime(2018, 1, 1) - pnow)
-> DateTime(2017, 12, 25, 2, 0, 0, tzinfo=Timezone('Europe/Berlin'))

 pnow + (pendulum.datetime(2018, 1, 1, tz='Europe/Berlin') - pnow)
-> DateTime(2017, 12, 25, 0, 0, 0, tzinfo=Timezone('Europe/Berlin'))

I am using pendulum==2.0.1

**Comment by sdispater** [comment]
@Benjamin-Setzer There is definitely a bug.

However, also note that you subtract two datetimes with different timezones: `pendulum.now()` sets the timezone to your local timezone while `pendulum.datetime()` sets it to `UTC`. So, you will not get the same result as with the `datetime` stdlib.

You can get the same result be using naive datetimes, even though it's not recommended, or by using datetimes in the same timezone:

```python
>>> import pendulum
>>> pnow = pendulum.now().naive()
>>> pnow + (pendulum.naive(2018, 1, 1) - pnow)
DateTime(2018, 1, 1, 0, 0, 0)
```

```python
>>> import pendulum
>>> pnow = pendulum.now()
>>> pnow + (pendulum.local(2018, 1, 1) - pnow)
DateTime(2018, 1, 1, 0, 0, 0,  tzinfo=Timezone('Europe/Berlin'))
```

**Comment by Benjamin-Setzer** [comment]
Thx for the tip. My timezone is 'Europe/Berlin', that's what the 2nd example is for.

**Comment by sdispater** [comment]
I can no longer reproduce this issue in the latest release so I am closing it.

Feel free to reopen if the bug still occurs on your side.
