### ISSUE TITLE
incorrect week of year for last week for year.

### ISSUE THREAD

**Issue by MSchuwalow** [sdispater/pendulum#221]
Dates falling into a week that spans 2 years seem to return an incorrect value of 1 for week of year.
A minimal example is:
dt = pendulum.datetime(2014, 12, 30)
assert dt.week_of_year == 1

**Comment by Benjamin-Setzer** [comment]
That's indeed correct behavior as defined by ISO:
https://en.wikipedia.org/wiki/ISO_week_date

there are other week numberings:
https://en.wikipedia.org/wiki/Week#Week_numbering

I personally like that it defaults to ISO

**Comment by MSchuwalow** [comment]
Alright. I'm closing the issue then.
Thanks for the help.
