### ISSUE TITLE
timestamp with miliseconds

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [sdispater/pendulum#222]
I would like to print unix time stamps (time since epoch) with milliseconds precision, there does not appear to be a function for this in the library.
Is there anyway to get a date in milliseconds since epoch?

**Comment by sdispater** [comment]
The `DateTime.float_timestamp` property gives you a timestamp with milliseconds precision (see https://pendulum.eustace.io/docs/#attributes-and-properties).

**Comment by jgrammen-agilitypr** [comment]
that actually gives you the timestamp in microsecond precision, as of the posting of this comment the timestamp since epoch in miliseconds is 
```
1529085780669
```
which has 13 digits.

the pendulum function in the example returns
```
>>> dt.float_timestamp
1346887571.123789
```
which has 16 digits (ignoring the period)

So guess the solution is to multiple by 1000 which gets me miliseconds and then drop everything after the decimal (the microsecond part).
