### ISSUE TITLE
module 'pendulum' has no attribute 'combine'

### ISSUE THREAD

**Issue by minibear0523** [sdispater/pendulum#223]
When I use pendulum.combine(date, time), which data and time is in correct type and format, but it throws an error `AttributeError: module 'pendulum' has no attribute 'combine'`

* pendulum version: 2.0.1
* python version: 3.6.3
* platform: centos 7.3+

**Comment by sdispater** [comment]
`combine()` is class method of the `DateTime` class not a top level function.
