### ISSUE TITLE
deepcopy of dict containing datetime  ~1000x slower with pendulum 1.4.1

### ISSUE THREAD

**Issue by touilleMan** [sdispater/pendulum#234]
```
$ python --version
Python 3.6.1
$ pip install pendulum==1.3.1
[...]
$ python -m timeit -s 'from copy import deepcopy; import pendulum' 'pendulum.now()' 
100000 loops, best of 3: 13.7 usec per loop
$ python -m timeit -s 'from copy import deepcopy; import pendulum; k={"foo": pendulum.now()}' 'deepcopy(k)' 
10000 loops, best of 3: 27.7 usec per loop
$ pip install pendulum==2.0.2
[...]
$ python -m timeit -s 'from copy import deepcopy; import pendulum' 'pendulum.now()' 
100000 loops, best of 3: 19.6 usec per loop
$ python -m timeit -s 'from copy import deepcopy; import pendulum; k={"foo": pendulum.now()}' 'deepcopy(k)' 
10 loops, best of 3: 27.4 msec per loop
```

So doing deepcopy on a dict containing a pendulum datetime has gone from 27usec to 27**msec**
Oddly enough deepcopy of the datetime object alone has remained roughly the same...

**Comment by touilleMan** [comment]
After bisect&test, it seems the version producing the trouble is 1.4.1
```
$ pip install pendulum==1.4.0
[...]
$ python -m timeit -s 'from copy import deepcopy; import pendulum; k={"foo": pendulum.now()}' 'deepcopy(k)' 
10000 loops, best of 3: 31.5 usec per loop
$ pip install pendulum==1.4.1
[...]
$ python -m timeit -s 'from copy import deepcopy; import pendulum; k={"foo": pendulum.now()}' 'deepcopy(k)' 
100 loops, best of 3: 5.91 msec per loop
```

I've updated this title of the issue accordingly

**Comment by touilleMan** [comment]
Hi @Secrus , you may also want to close PR #235 since it is related 

Out of curiosity, is there a reason for closing this issue after 5 years ? Is it just regular cleaning or did this issue has been solved in the meantime (or maybe the bug report is too old and you're not sure if the bug is still present anyway)

**Comment by Secrus** [comment]
> Out of curiosity, is there a reason for closing this issue after 5 years ? Is it just regular cleaning or did this issue has been solved in the meantime (or maybe the bug report is too old and you're not sure if the bug is still present anyway)

Regular cleaning and it was related to the old version (1.4.1) while we now have a new version. Feel free to open a new issue if you believe this is still relevant and can reproduce it.

**Comment by touilleMan** [comment]
@Secrus I've checked again I can confirm the issue is no longer here (commit https://github.com/sdispater/pendulum/commit/0a884dd36f1920a632681528a0251a9d6281aff1 from 3 months ago added the `__deepcopy__`) :+1:
