### ISSUE TITLE
offset_hours assumes integral timezone

### ISSUE THREAD

**Issue by schinckel** [sdispater/pendulum#24]
There are several timezones that don't have a integer offset from UTC: for instance Australia/Adelaide is +0930 (+1030 DST). This means that the following is incorrect:

    >>> import pendulum
    >>> pendulum.now('Australia/Adelaide).offset_hours
    9

Is this intentional? The documentation say "integer offset".

**Comment by sdispater** [comment]
Yes, It was intentional, it's supposed to represent the full number (as an integer) of hours in the offset.

However I can see why this might be a problem. So, you'd want it to return a float `9.5` or `10.5`?

**Comment by schinckel** [comment]
I'm interested in how this attribute is being used in the wild: I'm not sure of a situation where you would need the number of hours, rather than the offset as a timedelta.

There may be a situation where the integral number of hours is useful: I'm just not sure I can think of one.

(FWIW, some timezones are even less regular, IIRC there is a +0845 or something like that)

**Comment by sdispater** [comment]
Yes, I know, that's why I encourage you to use `offset` rather than `offset_hours`. `offset` gives you the offset in seconds.
I think, however, that `offset_hours` might come in handy in some cases.

**Comment by sdispater** [comment]
I just pushed a change on `master` that makes `offset_hours` return a float.

```python
>>> pendulum.from_timestamp(0, 'Australia/Adelaide').offset_hours
9.5
```
