### ISSUE TITLE
Python 3.7 - No matching distribution found for pendulum

### ISSUE THREAD

**Issue by Sn3akyP3t3** [sdispater/pendulum#247]
Doesn't appear to have support yet for Python 3.7.

**Comment by sdispater** [comment]
Pendulum supports Python 3.7, there is just no wheels yet for it. But it should work with the source distribution (tarball).

**Comment by Sn3akyP3t3** [comment]
Go ahead and close this.  I found a misconfiguration in my requirements.txt file that had http instead of https for the index that went unnoticed for years.

Set to --index-url https://pypi.python.org/simple/ and it works again.
