### ISSUE TITLE
Initialize from existing `datetime.date` object?

### ISSUE THREAD

**Issue by jacebrowning** [sdispater/pendulum#250]
`pendulum.instance(dt)` works for `datetime.datetime`, but how can I initialize a Pendulum object from an existing `datetime.date` (specifically a Django `DateField`)?

---

My current workaround:

```
pendulum.parse(str(date_object))
```

**Comment by oddProton** [comment]
```Python
from datetime.datetime import fromordinal as fromord
import pendulum
pendulum.instance(fromord(date_object.toordinal()))
```
This should work.

**Comment by oddProton** [comment]
You can also do this:

```Python
pendulum.datetime(date.year,date.month,date.day)
```

I don't think it's necessary to add it to the instance function.

**Comment by kakulukia** [comment]
+1

**Comment by trancee** [comment]
+1

I would also check for `datetime.time` so we have all possible cases of a datetime covered with Pendulum.

**Comment by joaodlf** [comment]
+1 This would be a great addition to the API!

**Comment by SemMulder** [comment]
+1

**Comment by silentwarrior** [comment]
+1

**Comment by racerthunder** [comment]
+1

**Comment by lonsun** [comment]
+1

**Comment by Alsanis** [comment]
+1

**Comment by rodrigondec** [comment]
+1

**Comment by madisvain** [comment]
I would like to pump this. I find doing this over and over and would love if pendulum had this feature built in.

**Comment by AaronBeaudoin** [comment]
This is a no-brainer for me. I work with an ORM that returns `datetime.date` instances, and having to pick them apart to pass them into `pendulum.instance` feels like the symptom of a missing feature.

**Comment by richieadler** [comment]
+1

**Comment by kakulukia** [comment]
I have created a first draft at https://github.com/kakulukia/pendulum .. im missing some tests before opening a puss request, but like to get some feedback first.

**Comment by blondelg** [comment]
+1

**Comment by yardensachs** [comment]
+1

**Comment by lena** [comment]
+1

**Comment by mcguigon0033** [comment]
+1

**Comment by jackb2113** [comment]
+1

**Comment by codytowstik** [comment]
+1 !

**Comment by FichteFoll** [comment]
I've also looked into the documentation & the code in search for this behavior. In the code, I see that even the shorthand class functions to initialize a `Date` like `today` first construct a native `datetime.date` object before they create the instance using its result. This surely would also profit from a `Date.instance` class function constructor.

https://github.com/sdispater/pendulum/blob/c4e518c950bcf0a4214b36c5992ae27d3c40e47f/pendulum/date.py#L740-L755
