### ISSUE TITLE
format() got an unexpected keyword argument 'formatter'

### ISSUE THREAD

**Issue by chriskoerner** [sdispater/pendulum#255]
As per documentation I did the following:

`import pendulum`
`dt = pendulum.now()`
`dt.format('[today] dddd', formatter='alternative')`

instead of receiving "'today Monday'"

I get: `"format() got an unexpected keyword argument 'formatter'"`

**Comment by Sn3akyP3t3** [comment]
I'm also experiencing this error using Python 3.7.

```
timezone = 'US/Central'

nowDate = pendulum.now(tz=timezone)

farthestWednesdayFromToday = nowDate.next(pendulum.WEDNESDAY).next(pendulum.WEDNESDAY)

print(closestWednesdayFromToday.format('MM/DD/YYYY', formatter='alternative'))
```
TypeError: format() got an unexpected keyword argument 'formatter'

**Comment by sdispater** [comment]
If you take a look at the Pendulum 2.0.0 annoucement (https://pendulum.eustace.io/blog/pendulum-2.0.0-is-out.html), it explicitely says that the alternative formatter is now the only one supported and, as such, the `formatter` keyword has been removed.
