### ISSUE TITLE
Parsing problems with Pendulum 2.0.3

### ISSUE THREAD

**Issue by richieadler** [sdispater/pendulum#259]
On PythonWin 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32:

The following raise `pendulum.parsing.exceptions.ParserError: Unable to parse string`

pendulum.parse('01-12-2017')
pendulum.parse('01/12/2017')
pendulum.parse('2017-1-17')
pendulum.parse('30-07-2018')

**Comment by sdispater** [comment]
These example are not considered standard by Pendulum and as such are not parsed by default.

If you want to have a looser parser, you can pass the `strict` keyword argument and set it to `False`:

```python
>>> import pendulum
>>> pendulum.parse("1-12-2017", strict=False)
DateTime(2017, 1, 12, 0, 0, 0, tzinfo=Timezone('UTC'))
>>> pendulum.parse("01/12/2017", strict=False)
DateTime(2017, 1, 12, 0, 0, 0, tzinfo=Timezone('UTC'))
>>> pendulum.parse('2017-1-17', strict=False)
DateTime(2017, 1, 17, 0, 0, 0, tzinfo=Timezone('UTC'))
>>> pendulum.parse('30-07-2018', strict=False)
DateTime(2018, 7, 30, 0, 0, 0, tzinfo=Timezone('UTC'))
```
