### ISSUE TITLE
.format('x') produces empty string

### ISSUE THREAD

**Issue by apnewberry** [sdispater/pendulum#262]
From the docs https://pendulum.eustace.io/docs/#formatter I think I can do `dt.format('x')` to get microseconds, but I'm just getting an empty string.

```python
>>> import pendulum
>>> pendulum.now().format('x')
''
>>> pendulum.__version__
'2.0.3'

```

Ubuntu 18.04, Python 3.6.5.

**Comment by dafinoer** [comment]
> From the docs https://pendulum.eustace.io/docs/#formatter I think I can do `dt.format('x')` to get microseconds, but I'm just getting an empty string.
> 
> ```python
> >>> import pendulum
> >>> pendulum.now().format('x')
> ''
> >>> pendulum.__version__
> '2.0.3'
> ```
> 
> Ubuntu 18.04, Python 3.6.5.

try to update to version 2.0.4.
