### ISSUE TITLE
Formatting string bug

### ISSUE THREAD

**Issue by lucas59356** [sdispater/pendulum#27]
I am using py3 and I tested the module in my locale (pt-br) but on formatting it returns a error:
ValueError: Invalid format string

**Comment by sdispater** [comment]
What exactly does your format string look like?

**Comment by lucas59356** [comment]
It  doesn't return anything, just a error. Note: I am only tested in the
pt-br locale, utc formattings works normally but on converting into "human
text" it doesn't work

2016-08-19 0:22 GMT-03:00 Sébastien Eustace <notifications@github.com>:

**Comment by sdispater** [comment]
Can you provide a sample of your code?

**Comment by lucas59356** [comment]
I am new in python and I has make something wrong while I try to generate a
"human time string" in my language like Sexta-Feira 19/08/2016 13:42.
That's a problem while I tryed to format a string, but I probably made
something wrong.
If you know how to make this, please help me if no bother :)

Sébastien Eustace <notifications@github.com> escreveu no dia sexta,
19/08/2016 às 10:04:

**Comment by sdispater** [comment]
It would be something like this:

```python
pendulum.now().format('%A %d/%m/%Y %H:%M', locale='pt_br')
```

To see how to format your instances see http://strftime.org and also https://pendulum.eustace.io/docs/#custom-directives for Pendulum's own additional directives.

**Comment by lucas59356** [comment]
Thanks :D

Em sex, 19 de ago de 2016 14:51, Sébastien Eustace <notifications@github.com>
escreveu:
