### ISSUE TITLE
Representing old dates

### ISSUE THREAD

**Issue by apnewberry** [sdispater/pendulum#278]
From https://en.wikipedia.org/wiki/Year_zero#ISO_8601,

> The "basic" format for year 0 is the four-digit form 0000, which equals the historical year 1 BC.

```python
>>> import pendulum
>>> pendulum.__version__
'2.0.3'
>>> pendulum.from_format('0000-01-01', 'YYYY-MM-DD')
ValueError: year 0 is out of range
```

This came up because [Matlab uses](https://www.mathworks.com/help/matlab/ref/datenum.html) "A serial date number represents the whole and fractional number of days from a fixed, preset date (January 0, 0000) in the proleptic ISO calendar."

Apparently [Astropy can handle](https://stackoverflow.com/a/19869864/3346095) old dates, as can [jdcal](https://pypi.org/project/jdcal/).

**Comment by sdispater** [comment]
Unfortunately, Pendulum relies on the `datetime` module which does not support year 0.

As it is there is nothing Pendulum can do since the promise is to be 100% compatible with the standard library.
