### ISSUE TITLE
How can get age in year, month, day

### ISSUE THREAD

**Issue by flaudizio** [sdispater/pendulum#28]
How can I get the age in this format: 32 years 3 months 45 days ?

I try to use:

age = pendulum.from_date(self.birth.year, self.birth.month, self.birth.day)

**Comment by sdispater** [comment]
This is not possible right now. The `age` property will just return the age in years (approximation).

You could do `age = date - date_of_birth` but it will return a`Period` that has a max unit of weeks, so you would have something like this : `342 weeks 24 days 13 hours 45 minutes 34 seconds`.

I will probably improve the `Period` class to support years and months.

**Comment by flaudizio** [comment]
Ok, thank you. Pendulum is so nice.
