### ISSUE TITLE
Convert datetime to Pendulum

### ISSUE THREAD

**Issue by bhy** [sdispater/pendulum#29]
Suppose I have some existing `datetime.datetime` objects, is their way to convert them to `Pendulum`?

**Comment by sdispater** [comment]
Yes, you can use the instance the `instance()` method:

```python
import pendulum
from datetime import datetime

dt = datetime(2016, 8, 20, 1, 2, 3)

pendulum.instance(dt)
# <Pendulum [2016-08-20T01:02:03+00:00]>

# You can also pass a timezone
pendulum.instance(dt, 'Europe/Paris')
# <Pendulum [2016-08-20T01:02:03+02:00]>
```

Be aware that you can only pass a naive-datetime or a datetime that has been localized by pendulum (see https://pendulum.eustace.io/docs/#using-the-timezone-library-directly) for now.

**Comment by bhy** [comment]
Thanks!

I should be able to figure this out if I read the document more thoroughly, instead of exploring the API via REPL. I was mainly looking at the `from_*` methods so I didn't find the `instance` method. Would you think method name `from_instance` or `from_native` or `from_pydatetime` be more discoverable?

**Comment by iv597** [comment]
I've also opened #31 which is the "kill a rat with a rocket launcher" method of solving this problem (albeit not originally designed to solve this ticket).

**Comment by sdispater** [comment]
@bhy I see why you would think that in would be a `from_*` method rather than just `instance()`. However, I like the conciseness of it.

I will think about it, since `from_instance()` might be more intuitive.

**Comment by ab-w** [comment]
The function name `pendulum.instance` is very unintuitive and difficult to find. I think it should be deprecated and the new function names should be `pendulum.from_pydatetime` and `pendulum.from_pydate`.

**Comment by Virusmater** [comment]
Found this issue from google and agree that names aren't so obvious.
Also I was able to convert python aware date to pendulum:
```python
def get_month_week(date, timezone):
    dt = pendulum.instance(date.astimezone(timezone))
    return dt.week_of_month
```
and it works as expected.
