### ISSUE TITLE
pendulum.duration documentation != console

### ISSUE THREAD

**Issue by wilfredinni** [sdispater/pendulum#292]
Hello there!
I need to convert periods of time to seconds, but while following the documentation:

![image](https://user-images.githubusercontent.com/23016174/47523692-031cf900-d86f-11e8-8499-c6095a457f88.png)

But instead:

```python
In [1]: import pendulum

In [2]: it = pendulum.duration(years=2, months=3)

In [3]: it.days
Out[3]: 820

In [4]: it.total_seconds()
Out[4]: 0.0
```

Also, when trying to convert a month to seconds:

```python
In [9]: it = pendulum.duration(months=3)

In [10]: it.total_seconds()
Out[10]: 0.0
```

But this works with days:

```python
In [5]: it = pendulum.duration(days=3)

In [6]: it.total_seconds()
Out[6]: 259200.0
```

Or maybe I'm not reading this right. Thanks

**Comment by Secrus** [comment]
This works fine in the most recently released version (2.1.2).
