### ISSUE TITLE
Issue with in_tz() method: NO time conversion

### ISSUE THREAD

**Issue by Tez-O** [sdispater/pendulum#324]
Dear Sir/Madam,

Your documentation web page has the following example in using in_tz():
![example](https://user-images.githubusercontent.com/45790660/49802832-10dbfe80-fd89-11e8-8270-436aff7c6784.JPG)

When I use it on Jupyter Lab with a 'Asia/Singapore' tz string, the function in_tz does not convert UTC time to that of Singapore at all (see the output below plus the attached file of Jupyter Lab)
![issue](https://user-images.githubusercontent.com/45790660/49802845-1df8ed80-fd89-11e8-85fb-0ada8281191b.JPG)

Neither does it work for 'Asia/Tokyo'...
![tokyo](https://user-images.githubusercontent.com/45790660/49803101-df176780-fd89-11e8-9b9f-79cd1f81e6f9.JPG)

Is there any code missing to obtain the correct conversion?

**Comment by sdispater** [comment]
`in_tz()` will do the conversion while `set(tz=...)` will not and leave the time as is. In you example, you are only using `set()` so, obviously the conversion won't happen.

```python
>>> import pendulum
>>> dt = pendulum.datetime(2013, 3, 31, 2, 30)
>>> print(dt.in_tz("Asia/Singapore"))
'2013-03-31T10:30:00+08:00'
>>> print(dt.set(tz="Asia/Singapore"))
'2013-03-31T02:30:00+08:00'
```
