### ISSUE TITLE
Website Supported Timezones Strings Dead Link

### ISSUE THREAD

**Issue by liquidgenius** [sdispater/pendulum#327]
In the [website documentation under Instantiation](https://pendulum.eustace.io/docs/#instantiation) the statement "Supported strings for timezones are the one provided by the IANA time zone database." leads to a dead link.

Where are the supported timezone strings listed now?

![screen shot 2018-12-29 at 11 37 17 am](https://user-images.githubusercontent.com/3987909/50540349-370de680-0b5e-11e9-93df-116df1a55bc4.png)

**Comment by Secrus** [comment]
The link seems to work fine now.
