### ISSUE TITLE
Interval.in_words() support for sub second values

### ISSUE THREAD

**Issue by mayfield** [sdispater/pendulum#33]
I like the in_words()/**str**() behavior of Interval objects.  However I sometimes have intervals that are sub-second and it would be nice if those resolved to something like '25ms' instead of just an empty string ''.

I could submit a pull request with such a change if you like.

**Comment by sdispater** [comment]
I agree that would be a nice addition. Feel free to submit a pull request :-)

**Comment by mayfield** [comment]
I started working on this and got blocked trying to instrument a test case by #34 ;  Let me know what you think about that issue and I'll course correct as needed.  I usually write the failing test case first and then implement the fix, but I can just provide a sussed out PR without a test-case if my platform is just being silly.

**Comment by sdispater** [comment]
I just figured that it might be more difficult, or at least more complex, than expected since `in_words()` is localizable, so we would have to provide translations for sub second units.

**Comment by sdispater** [comment]
@mayfield After thinking about it, maybe the best approach here is, instead of an empty string, to return a string with fractional seconds like `0.5 seconds`.

What do you think?
