### ISSUE TITLE
not bug) About name of pendulum

### ISSUE THREAD

**Issue by joyongjin** [sdispater/pendulum#330]
I think the name of the `pendulum` would disrupts the usability of this package. Because it is too long and cumbersome to type. (Maybe because I'm a non-English speaker.)

I made wrapper of `pendulum` for short name. But It would be nice to provide a short name on its own, I guessed.

[pend repository](https://github.com/joyongjin/pend)

If this is not a big problem, please close this issue.

**Comment by Ocupe** [comment]
I think you have more than enough options to ease your typing burden.
```
import pendulum as pend
pend.now()
# or
import pendulum as p
p.now()
# or
from pendulum import now
now()
```

A general note: You should think about if the question you want to ask is related to the given project or not. A general question, like yours, should be ask on stackoverflow or similar places. Asking unrelated questions just puts burden on the people maintaining the project.

**Comment by joyongjin** [comment]
@Ocupe I opened this issue because I thought the name of the pendulum would disrupts the usability of this package. So I wanted to discuss whether there was a solution at the package level. But if it doesn't matter much, I apologize.

**Comment by vlt** [comment]
> and cumbersome to type

reading > writing

I'm in favour of closing this issue.
