### ISSUE TITLE
Loader.load portability broken for some pytz installs

### ISSUE THREAD

**Issue by mayfield** [sdispater/pendulum#34]
I don't know the full details that make my platform not work with `Loader.load` but I'm using a Fedora Core 24 box with its stock python3.5 interpretor.  I believe that the `pytz` install I have was installed by pip3 but I'm not 100% sure.

When I run tests most of them fail because `Loader.load` is trying to open zoneinfo files in a location that they don't exist.  Looking at the code it looks like this is a possibly a non portable way of getting zoneinfo since it makes assumptions about where the zoneinfo files should live.

I tweaked the exception to print the file location to illustrate..

```
======================================================================
ERROR: wrap_with_test_now (tests.tz_tests.test_timezone.TimezoneTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mayfield/project/pendulum/tests/__init__.py", line 13, in setUp
    LocalTimezone.set_local_timezone(timezone('America/Toronto'))
  File "/home/mayfield/project/pendulum/pendulum/tz/__init__.py", line 16, in timezone
    return Timezone.load(name)
  File "/home/mayfield/project/pendulum/pendulum/tz/timezone.py", line 50, in load
    default_transition_type) = Loader.load(name)
  File "/home/mayfield/project/pendulum/pendulum/tz/loader.py", line 28, in load
    raise TypeError(filepath)
TypeError: /usr/lib/python3.5/site-packages/pytz/zoneinfo/America/Toronto
```

In that case there is not a `zoneinfo` sub dir in `/usr/lib/python3.5/site-packages/pytz`.  But on the same machine this works fine..
```
>>> pytz.timezone('America/Toronto')
<DstTzInfo 'America/Toronto' LMT-1 day, 18:42:00 STD>
```

**Comment by sdispater** [comment]
That's odd. What is the output of the following?

```python
>>> import pytz
>>> import os
>>> import inspect

>>> os.path.dirname(inspect.getfile(pytz))
```

More importantly, does it return `/usr/lib/python3.5/site-packages/pytz`

**Comment by mayfield** [comment]
`'/usr/lib/python3.5/site-packages/pytz'`

Which is there, it just doesn't have a zoneinfo dir.

**Comment by mayfield** [comment]
So in my install the zoneinfo files are shared with the system...

```
>>> import pytz
>>> pytz.open_resource('adsf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pytz/__init__.py", line 90, in open_resource
    return open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/zoneinfo/adsf'
```

That open_resource function from pytz might be your huckleberry.

**Comment by sdispater** [comment]
Which version of `pytz` do you have?

**Comment by sdispater** [comment]
Here is the `open_resource` function from `pytz`:

```python
def open_resource(name):
    """Open a resource from the zoneinfo subdir for reading.

    Uses the pkg_resources module if available and no standard file
    found at the calculated location.
    """
    name_parts = name.lstrip('/').split('/')
    for part in name_parts:
        if part == os.path.pardir or os.path.sep in part:
            raise ValueError('Bad path segment: %r' % part)
    filename = os.path.join(os.path.dirname(__file__),
                            'zoneinfo', *name_parts)
    if not os.path.exists(filename):
        # http://bugs.launchpad.net/bugs/383171 - we avoid using this
        # unless absolutely necessary to help when a broken version of
        # pkg_resources is installed.
        try:
            from pkg_resources import resource_stream
        except ImportError:
            resource_stream = None

        if resource_stream is not None:
            return resource_stream(__name__, 'zoneinfo/' + name)
    return open(filename, 'rb')
```

So, it seems that some pkg_resources version are broken and the `zoneinfo` directory is missing.

Pendulum needs to use the `open_resource` from `pytz` to fix the problem.

**Comment by mayfield** [comment]
re: version  

>>> import pytz
>>> pytz.__version__
'2016.6.1'

**Comment by mayfield** [comment]
Yeah, how about a patch like this (untested)...

```patch
:; git diff pendulum/tz/loader.py | cat
diff --git a/pendulum/tz/loader.py b/pendulum/tz/loader.py
index 296854a..38bebff 100644
--- a/pendulum/tz/loader.py
+++ b/pendulum/tz/loader.py
@@ -15,16 +15,8 @@ class Loader(object):
     @classmethod
     def load(cls, name):
         name = decode(name)
-
-        name_parts = name.lstrip('/').split('/')
-
-        for part in name_parts:
-            if part == os.path.pardir or os.path.sep in part:
-                raise ValueError('Bad path segment: %r' % part)
-
-        filepath = os.path.join(cls.path, *name_parts)
-
-        if not os.path.exists(filepath):
+        try:
+            with pytz.open_resource(name) as f:
+                return Parser._parse(f)
+        except OSError:
             raise ValueError('Unknown timezone [{}]'.format(name))
-
-        return Parser.parse(filepath)
```

**Comment by mayfield** [comment]
I tested that and added a couple tests to validate the loader contract (ie. return ValueError when the timezone is not found instead of a FileNotFoundError (OSError for pre py3k).  I can submit a PR on that if you like.

**Comment by sdispater** [comment]
Thanks.

For more simplicity, it's possible to just do the `with open_resource()` in the public `Parser.parse()` method.

```python
class Parser(object):

    @classmethod
    def parse(cls, name):
        try:
            with open_resource(name) as fp:
                return cls._parse(fp)
        except OSError:
             raise ValueError('Unknown timezone [{}]'.format(name))
```

And the `Loader` to become:

```python
class Loader(object):

    @classmethod
    def load(cls, name):
        name = decode(name)

        return Parser.parse(name)
```

It would remove a lot of the purpose of the `Loader` class (except for decoding the name) but I think it would be more logical. 

What do you think?

**Comment by mayfield** [comment]
Works for me.  Is there any reason not to move the decode to Parser too and just deprecate Loader?

**Comment by sdispater** [comment]
Yeah. We should deprecate one or the other.

I think the best approach here is just to remove `Parser` and move its methods to the loader class, since the name `Parser` is not exactly clear about what its purpose is.

**Comment by sdispater** [comment]
Do you want me to make this change or are you making a pull request?

**Comment by mayfield** [comment]
I can submit a PR.

**Comment by sdispater** [comment]
Great! Thank you :-)
