### ISSUE TITLE
Daylight savings time

### ISSUE THREAD

**Issue by yuggieg** [sdispater/pendulum#367]
Came across this when looking at the examples. Not sure if it's a bug or that I'm just misunderstanding the logic:

```
>>> print(pendulum.datetime(2013, 3, 31, 2, 30, tz="UTC"))
2013-03-31T02:30:00+00:00 #all good
>>> print(pendulum.datetime(2013, 3, 31, 2, 30, tz="Europe/Paris"))
2013-03-31T03:30:00+02:00 #why 3:30??
>>> print(pendulum.datetime(2013, 3, 1, 2, 30, tz="Europe/Paris"))
2013-03-01T02:30:00+01:00 # this makes sense again
>>> print(pendulum.datetime(2013, 4, 1, 2, 30, tz="Europe/Paris"))
2013-04-01T02:30:00+02:00 # this also makes sense
```
In all of the cases I would expect the time to be 2:30, but in the second example it is actually 3:30. What am I missing here? It shows the same issue in your documentation (under Fluent helpers). It seems to have something to do with daylight savings (the second is just past DST (ends at 2:00 in Paris), third is not DST, fourth is DST).

**Comment by sdispater** [comment]
The explanation is in the documentation: https://pendulum.eustace.io/docs/#normalization

This is the expected behavior.
