### ISSUE TITLE
Can't import pendulum inside a test file using pytest

### ISSUE THREAD

**Issue by decko** [sdispater/pendulum#37]
Importing pendulum inside a test file and running pytest returns an error about importing language files.

Running the following code:
```python
import pytest
import pendulum

def test_import_pendulum():
    date = pendulum.now(tz='America/Sao_Paulo')
    assert data.is_today() == True
```

returns the following message:
```
ImportError while importing test module '/home/decko/dev/temp/test_pendulum.py'.
Original error message:
'No module named no'
Make sure your test modules/packages have valid Python names.
```

**Comment by sdispater** [comment]
Thanks for reporting this.

It seems that the locale module `no` was not integrated into the newest (0.5.3) release for some reason.

I will try to push a hotfix release quickly to resolve this.

For the time being, please install the previous version:

`pip install pendulum==0.5.2`

**Comment by sdispater** [comment]
I just released a new version (0.5.4) that should fixed the issue.

**Comment by decko** [comment]
Great! It's seems that the problem is solved! Thanks a lot!

**Comment by sdispater** [comment]
You're welcome :-)
