### ISSUE TITLE
"Africa/Casablanca" and "Africa/El_Aaiun" time_zone key raise exception when constructing datetime object

### ISSUE THREAD

**Issue by qianshuinixing** [sdispater/pendulum#370]
for example
`import pendulum`
`t = pendulum.datetime(2018, 1, 1, 1, 1, 0, tz='Africa/Casablanca')`

raise exception:
`
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pendulum/tz/zoneinfo/posix_timezone.py", line 41, in posix_spec
    raise InvalidPosixSpec(spec)
pendulum.tz.zoneinfo.exceptions.InvalidPosixSpec: Invalid POSIX spec: 
`

**Comment by qianshuinixing** [comment]
Latest commit has resolve this problem , https://github.com/sdispater/pendulum/commit/94d28b0d3cb524ae02361bd1ed7ea03e2e655e4e
Can you release the latest version？ @sdispater

**Comment by mattLLVW** [comment]
Any infos about a new release?

**Comment by aruvalcaba** [comment]
Any reason this hasn't been merged and released?

**Comment by sdispater** [comment]
A new version has been released.
