### ISSUE TITLE
Support negative ISO 8601 dates

### ISSUE THREAD

**Issue by fdw** [sdispater/pendulum#378]
It seems that Pendulum cannot parse dates from BCE, ex `pendulum.parse('-0100-07-12')`, throwing a `ParserError` instead.

According to [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Years), in these cases the year should have a `-` prefix. I couldn't find any alternative syntax for Pendulum, either.

**Comment by sdispater** [comment]
The standard library does not support negative datetimes and since Pendulum inherits from it, it can't support it either.

**Comment by dekoza** [comment]
I wonder if this could be patched in somehow. I'm working on GEDCOMX implementation and wanted to use `pendulum` but lack of negative dates forces me to do come hacking :thinking:
