### ISSUE TITLE
Difference between timezones is always 0

### ISSUE THREAD

**Issue by matcool** [sdispater/pendulum#389]
I wanted to check the hours difference between two timezones, but instead I got 0
Example: (this happens with any two timezones)
```python
>>> a = pendulum.now('America/New_York')
>>> b = pendulum.now('Europe/Berlin')
>>> a.diff(b).in_hours()
0
```

**Comment by zeebonk** [comment]
Hi @matcool, I'm not one of the maintainers, but might be able to help you out:

`dt1.diff(dt2)` return time time between the moments that d1 and d2 occur. As you're specifically asking for `now`, but in two different timezones, it will be the same 'moment' of time, and therefore difference is 0.

To look it from a different angle, if you would screen "HEY" _now_ while being in New York, and I would screen "HEY" _now _in Berlin, we will be screaming "HEY" at the same time: 0 hours difference.

If you want the difference in timezone offsets, you can use the `offset` property, which specifies the +/- number of seconds offset from UTC:

```py
In [14]: (pendulum.now('Europe/Berlin').offset - pendulum.now('America/New_York').offset) / 3600
Out[14]: 6.0
