### ISSUE TITLE
DST issue for Africa/Casablanca

### ISSUE THREAD

**Issue by letsprog** [sdispater/pendulum#400]
Hello! Currently there is a timezone issue for Africa/Casablanca, as DST is not considered and for the summer time it becomes +0100.

```
>>> pendulum.parse('2000-07-01T09:30+0000').in_timezone('Africa/Casablanca').isoformat()
'2000-07-01T09:30:00+00:00'
>>> pendulum.parse('2000-01-01T09:30+0000').in_timezone('Africa/Casablanca').isoformat()
'2000-01-01T09:30:00+00:00'
```
I have installed pendulum today (23 Aug) using pip in a macos and this is the installed version :
```
>>> print(pendulum.__version__)
2.0.5
```
I read that the issue was resolved in this ticket but it's not clear for me in which version specially that I have just installed pendulum today : https://github.com/sdispater/pendulum/issues/370

Thank you

**Comment by sdispater** [comment]
I don't understand. The `Africa/Casablanca` timezone did not observe offset changes from 1986 up to 2008 where it had no difference from the `UTC` timezone. The result you are seeing is the expected one.

**Comment by letsprog** [comment]
What about the change that happened in 2018? https://en.wikipedia.org/wiki/Daylight_saving_time_in_Morocco
But it's okay I will do a patch to the library.
Thank you
