### ISSUE TITLE
Issue with Python 3.2

### ISSUE THREAD

**Issue by guyzmo** [sdispater/pendulum#41]
I installed pendulum on Python 3.2 install, and when I run it, here's what I get:

``` python
 % python3
Python 3.2.3 (default, Feb 20 2013, 17:02:41) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/pendulum/__init__.py", line 3, in <module>
    from .pendulum import Pendulum
  File "/usr/local/lib/python3.2/dist-packages/pendulum/pendulum.py", line 19, in <module>
    from .tz import Timezone, UTC, FixedTimezone, local_timezone
  File "/usr/local/lib/python3.2/dist-packages/pendulum/tz/__init__.py", line 3, in <module>
    from .timezone import Timezone, FixedTimezone, UTC
  File "/usr/local/lib/python3.2/dist-packages/pendulum/tz/timezone.py", line 6, in <module>
    from .loader import Loader
  File "/usr/local/lib/python3.2/dist-packages/pendulum/tz/loader.py", line 10, in <module>
    from .. import _compat
  File "/usr/local/lib/python3.2/dist-packages/pendulum/_compat.py", line 19, in <module>
    FileNotFoundError = FileNotFoundError
NameError: name 'FileNotFoundError' is not defined
```

It looks like the `FileNotFoundError`exception, along with the rework of the OS/IO exceptions has been introduced in Python 3.3.
cf 

I do not understand why `FileNotFoundError` could not defined in Python 3.2. cf [PEP-3151](https://www.python.org/dev/peps/pep-3151/)

Instead of relying on major python versions to check for features, I'd suggest to check for the feature and fallback to the alternative. Such as:

``` python
try:
   FileNotFoundError = FileNotFoundError
except NameError:
   FileNotFoundError = IOError
```

The Python3.2.3 I'm using, is the one from Debian Wheezy (old-stable) and I installed pendulum v0.5.5 from Pypi. I tried with the suggested fix above, and it works.

**Comment by sdispater** [comment]
It is linked to #34 and its associated pull request #35.

I will make the change to fix this :-)

**Comment by guyzmo** [comment]
indeed ☺

I was actually thinking of doing a PR anyway, just wanted to understand the .so issue in the other ticket first, though ☺

**Comment by guyzmo** [comment]
actually, a good fix could be:

```
FileNotFoundError = getattr(__builtins__, 'FileNotFoundError', IOError)
```

though it's always nicer to avoid using introspection builtins like `getattr`, I think it's a pretty good way to cover all cases.

**Comment by sdispater** [comment]
Go ahead if you want to make a PR :-)

I prefer:

```python
try:
   FileNotFoundError = FileNotFoundError
except NameError:
   FileNotFoundError = IOError
```

to be honest. It seems more explicit.
