### ISSUE TITLE
Subtracting negative timedelta around DST not same as adding the positive

### ISSUE THREAD

**Issue by tomage** [sdispater/pendulum#420]
Hey! As I've been digging deeper into the Pendulum library, I've discovered one interesting edge-case: Namely that for specific times, subtracting a negative timedelta is not the same as adding the positive one.

Thus, `my_dt - my_negative_timedelta` is not equal to `my_dt + (-my_negative_timedelta)`.

As before, I took the liberty of throwing together what seemed a sensible patch: https://github.com/sdispater/pendulum/pull/419.

Here's also a pyfiddle, to see this in action: https://pyfiddle.io/fiddle/6a20e200-bb3a-4af9-b336-a216f868487d/.

Thanks!

**Comment by teresatruex** [comment]
I am seeing the same issue! Is this a bug? Please let us know!

**Comment by shuyang-truex** [comment]
I'm experiencing the same issue, my code snippet below:

```
import pendulum
from pendulum import datetime
from datetime import timedelta

la_tz = pendulum.timezone('America/Los_Angeles')

d = datetime(2019, 11, 4, hour=0, tzinfo=la_tz)
```
 and console output:
```
>>> d - timedelta(hours=24)
<Pendulum [2019-11-03T00:00:00-07:00]>
>>> d + timedelta(hours=-24)
<Pendulum [2019-11-03T01:00:00-07:00]>
```

Hope we can get some attention from the maintainers on this issue.

**Comment by tomage** [comment]
Fixed with https://github.com/sdispater/pendulum/pull/419#event-3512837708!
