### ISSUE TITLE
Cannot check == between Period and timedelta

### ISSUE THREAD

**Issue by shabbyrobe** [sdispater/pendulum#421]
Hello, I'm having trouble comparing the result of subtracting two DateTimes with a `timedelta`. If I run the following snippet:

```py
import pendulum
from pendulum.period import Period
from datetime import timedelta
d1 = pendulum.datetime(2019, 1, 2, tz='UTC')
d2 = pendulum.datetime(2019, 1, 1, tz='UTC')
period = d1 - d2
print(period == timedelta(days=1))
```

I get the following error, instead of the `True` I was expecting:

```
AttributeError: 'datetime.timedelta' object has no attribute 'start'
```

**Comment by wakemaster39** [comment]
Comparison against anything that was not a Period was broken, opened a PR to fail over to Duration if `other` is not a Period.
