### ISSUE TITLE
RecursionError when add or subtract-ing with a fixed offset timezone

### ISSUE THREAD

**Issue by euan-dietchef** [sdispater/pendulum#422]
The following:
```
import pendulum
pendulum.datetime(2019, 11, 1, tz=pendulum.tz.fixed_timezone(0)).subtract(seconds=1)
```
```
import dateutil, pendulum
pendulum.datetime(2019, 11, 1, tz=dateutil.tz.tzoffset(name=None, offset=0)).subtract(seconds=1)
```
```
import aniso8601, pendulum
pendulum.datetime(2019, 11, 1, tz=aniso8601.utcoffset.UTCOffset(minutes=0)).subtract(seconds=1)
```
all result in this RecursionError:
```
  ....
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 66, in convert
    return self._convert(dt)
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 334, in _convert
    return dt.astimezone(self)
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 1466, in astimezone
    return pendulum.instance(super(DateTime, self).astimezone(tz))
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 345, in fromutc
    return (dt + self._utcoffset).replace(tzinfo=self)
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 1442, in __add__
    return self._add_timedelta(other)
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 750, in _add_timedelta
    return self.add(seconds=delta.total_seconds())
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 660, in add
    dt = self.tz.convert(dt)
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 66, in convert
    return self._convert(dt)
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 334, in _convert
    return dt.astimezone(self)
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 1466, in astimezone
    return pendulum.instance(super(DateTime, self).astimezone(tz))
  File "/usr/local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 345, in fromutc
    return (dt + self._utcoffset).replace(tzinfo=self)
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 1442, in __add__
    return self._add_timedelta(other)
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 750, in _add_timedelta
    return self.add(seconds=delta.total_seconds())
  File "/usr/local/lib/python3.8/site-packages/pendulum/datetime.py", line 621, in add
    offset = self.utcoffset()
RecursionError: maximum recursion depth exceeded
```

The actual date, offset, or number of seconds to add/subtract doesn't seem to matter, and using 'add' instead of subtract also causes the issue. A 'normal' timezone like 'Europe/London' won't cause the issue.

This came up with dates returned from our graphql API (which are parsed by graphene using aniso8601). Since all the fixed-offset tzinfo objects above trigger the same issue, I'm not sure what a good workaround would be, other than finding a 'normal' timezone that happens to have the same offset.

This is on CPython 3.8.0 on Linux, and I've tried with pendulum 2.0.4 and 2.0.5. I can't repro the issue on CPython 3.7.4, so I'm assuming it's 3.8-specific.

The closest existing issue I could find is https://github.com/sdispater/pendulum/issues/361 , but doesn't seem related - it's PyPy-specific, and `in_timezone` works okay on my example datetimes above.

**Comment by zeburek** [comment]
Also reproduced with just adding and substucting minutes (without any other params).

**Comment by FlynDice** [comment]
Adding/subtracting years, months, weeks, days works fine.  hours, minutes, seconds, microseconds cause  RecursionError

**Comment by NomAnor** [comment]
I've got the same error. Looking at the stacktrace and code it seems to me the problem is with the `FixedTimezone` class.
https://github.com/sdispater/pendulum/blob/bc32743b3d9a7d59cc005fc82a7842c5abff84b0/pendulum/tz/timezone.py#L344-L345
uses `astimezone()` indirecly through `__add__()` and
https://github.com/sdispater/pendulum/blob/bc32743b3d9a7d59cc005fc82a7842c5abff84b0/pendulum/tz/timezone.py#L332-L336

But the python documentation states that 

> This [fromutc()] is called from the default datetime.astimezone() implementation.

which results in the recursion. `fromutc()` should be implemented so `astimezone()` works which means it can't use `astimezone()` itself.

The use of `replace(tzinfo=self)` should be unnecessary because

> When a datetime object is passed in response to a datetime method, dt.tzinfo is the same object as self. tzinfo methods can rely on this, unless user code calls tzinfo methods directly. The intent is that the tzinfo methods interpret dt as being in local time, and not need worry about objects in other timezones.

Maybe this is violated somewhere in the pendulum code?

Can someone with more knowledge about the pendulum code look over this?

**Comment by kokon** [comment]
Does anyone have a good way to workaround this issue?

**Comment by kokon** [comment]
Thanks for the pointer @NomAnor . I currently worked around this by adding these lines on `fromutc()`:
```
    def fromutc(self, dt):  # type: (datetime) -> datetime
        if dt.__class__ is not datetime:
            kwargs = {"tzinfo": dt.tzinfo}
            if _HAS_FOLD:
                kwargs["fold"] = dt.fold
            dt = datetime(
                dt.year,
                dt.month,
                dt.day,
                dt.hour,
                dt.minute,
                dt.second,
                dt.microsecond,
                **kwargs
            )

        return (dt + self._utcoffset).replace(tzinfo=self)
```
This will force the `dt` to be a `datetime` instance, thus avoids the `__add__()` call that caused the infinite recursion.
I'm not sure if this is the best way to fix it, but it seems to work in my case.

**Comment by Tinche** [comment]
We've been affected by this as well since upgrading to 3.8, for example when generating DateTime instances from BSON ObjectIds. Any hope of this getting fixed?
