### ISSUE TITLE
python type annotations for PEP-561 compliance

### ISSUE THREAD

**Issue by johnjiang** [sdispater/pendulum#432]
As python has gotten better and better support for type annotations we should add support for type annotations inside pendulum.

Thankfully there's already a PR open for this:

https://github.com/sdispater/pendulum/pull/320 

Happy to help out in any way possible to get this through the finish line.

**Comment by pikeas** [comment]
This would be great to have! For example, it would be nice if this snippet was type-aware:

```
period = pendulum.period(start, end)
for dt in period.range("hours"):
    pass
```

**Comment by Secrus** [comment]
Fixed in the next release.

**Comment by reagle** [comment]
I'm wondering when the next release might be? (2.1.2 was 3 years ago.)
