### ISSUE TITLE
DateTime should declare itself as a subclass of datetime

### ISSUE THREAD

**Issue by wosc** [sdispater/pendulum#434]
Something really strange is going on

```python
>>> a = pendulum.now()
>>> a.__class__.__bases__
(<type 'datetime.datetime'>, <class 'pendulum.date.Date'>)
>>> isinstance(a, datetime.datetime)
False
```

Surely `isinstance` should return `True` here?!

**Comment by vamega** [comment]
What version of Python and pendulum are you using?
I can't seem to replicate on pendulum 2.1.0 and Python 3.7.6

```python
>>> isinstance(pendulum.now(), datetime.datetime)                          
True
```

**Comment by wosc** [comment]
Sorry, I should have specified the versions, that was sloppy of me.
It was pendulum 2.0.5 under Python 2.7. But funnily enough, I cannot reproduce it with these versions anymore, either. I'm _certain_ I reproduced this in a clean virtualenv in January, but since I cannot anymore I guess that's a moot point.
