### ISSUE TITLE
No playable streams found on this URL

### ISSUE THREAD

**Issue by boygiandi** [sdispater/pendulum#436]
I tried this

> streamlink -l debug 'https://www.youtube.com/watch?v=7sd7DTMWzFQ&feature=youtu.be'

> [cli][debug] OS:         Linux-4.19-ovh-xxxx-std-ipv6-64-x86_64-with-centos-7.7.1908-Core
> [cli][debug] Python:     2.7.5
> [cli][debug] Streamlink: 1.3.0+24.g40c732c
> [cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
> [cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=7sd7DTMWzFQ&feature=youtu.be
> [plugin.youtube][debug] Video ID from URL
> [plugin.youtube][debug] Using video ID: 7sd7DTMWzFQ
> [plugin.youtube][debug] get_video_info - 1: Found data
> error: No playable streams found on this URL: https://www.youtube.com/watch?v=7sd7DTMWzFQ&feature=youtu.be

> streamlink --version
> streamlink 1.3.0+24.g40c732c

Please check and fix it. Thank you

**Comment by richard-scott** [comment]
Maybe try this repo: https://github.com/streamlink/streamlink/issues
