### ISSUE TITLE
latest pyyaml (5.3) requires python >=3.5

### ISSUE THREAD

**Issue by wakemaster39** [sdispater/pendulum#442]
A number of dev dependencies require pyyaml which the latest version does not support python 3.4 which is causing a number of builds to fail. There is no poetry.lock file included in the library so builds are grabbing latests which is breaking.

Two solutions, not sure which you want best:
1. Removed python 3.4 support.
2. Add a pyyaml as a dev dependency lock to version 5.2.*

**Comment by Secrus** [comment]
This is now fixed with proper `poetry.lock` and the required Python version being >=3.5 (or 3.7 with the master branch).
