### ISSUE TITLE
Period exclusion from a list of periods functionality

### ISSUE THREAD

**Issue by AndreasBackx** [sdispater/pendulum#46]
I have a small library written in [Kotlin](https://kotlinlang.org) similar to Pendulum's Period functionality and added an exclusion function. It would 'remove' and edit periods from a list of periods based on the period that needs to be excluded. I would love to submit a PR and add the feature to Pendulum. Here's an example:

```python
periods = [
    Period(
        start=yesterday,
        end=tomorrow
    )
]

excluded_periods = Period.exclude(
    periods=periods,
    exclusion=Period(
        start=today,
        end=tomorrow
    )
)
[
    Period(
        start=yesterday,
        end=today
    )
]
```

Could we perhaps talk on the Slack you mentioned in #42? Send me a message on [Twitter](https://twitter.com/AndreasBackx) for my email address.

**Comment by AndreasBackx** [comment]
Besides the exclusion I also have implemented a way to merge overlapping periods in a list of periods  in my own library . It would be great to have this feature in Pendulum too. I do a lot of work with opening hours and the kind and am really looking for a python implementation of what I already have.

**Comment by sdispater** [comment]
The syntax you provided does not feel intuitive to me.

However, giving a way to exclude on or more periods from another and getting the intersection of 2 periods seems like good ideas :-)

The way I see things is:

```python
>>> from pendulum import period, today

>>> today = today()
# <Pendulum [2016-09-07T00:00:00-05:00]>
>>> yesterday = today.subtract(days=1)
# <Pendulum [2016-09-06T00:00:00-05:00]>
>>> next_week = today.add(weeks=1)
# <Pendulum [2016-09-14T00:00:00-05:00]>
>>> previous_week = today.subtract(weeks=1)
# <Pendulum [2016-08-31T00:00:00-05:00]>

>>> global_period = period(previous_week, next_week)
# <Period [2016-08-31T00:00:00-05:00 -> 2016-09-14T00:00:00-05:00]>
>>> global_period.exclude(period(yesterday, today))
#[<Period [2016-08-31T00:00:00-05:00 -> 2016-09-05T00:00:00-05:00]>,
# <Period [2016-09-08T00:00:00-05:00 -> 2016-09-14T00:00:00-05:00]>]

>>> global_period.exclude([period(yesterday, today), period(today.add(days=3), today.add(days=5))])
#[<Period [2016-08-31T00:00:00-05:00 -> 2016-09-05T00:00:00-05:00]>,
# <Period [2016-09-08T00:00:00-05:00 -> 2016-09-09T00:00:00-05:00]>,
# <Period [2016-09-13T00:00:00-05:00 -> 2016-09-14T00:00:00-05:00]>]

>>> period(yesterday, today).intersect(global_period)
# <Period [2016-09-06T00:00:00-05:00 -> 2016-09-07T00:00:00-05:00]>
```

For more complex use cases, I think relying on `map()` and `filter()` should do the trick.

**Comment by AndreasBackx** [comment]
Looks solid, I've got most of the code written already. I'll make the changes and make a PR.

What do you think of the following small change for excluding lists?

From:
```python
global_period.exclude([period(yesterday, today), period(today.add(days=3), today.add(days=5))])
```

To:
```python
global_period.exclude(period(yesterday, today), period(today.add(days=3), today.add(days=5)))
```

I removed the brackets, we could just use `*periods` in the signature.

I'm not gonna add `intersect()` just yet btw.
