### ISSUE TITLE
Datetime.format produces incorrect time

### ISSUE THREAD

**Issue by jeliashi** [sdispater/pendulum#460]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: 10.15.4 Mac OS Catalina
- **Pendulum version**: 2.1.0

## Issue

Pendulum datetime format prints time - 12 hours
```
import pendulum
tnow = pendulum.now().astimezone(pendulum.UTC)
print(tnow)
print(tnow.format('YMMDDThhmmss'))
```
returns:
```
2020-04-06T18:29:43.054288+00:00
20200406T062943
```

**Comment by sdispater** [comment]
You are using the `hh` token for the hours which effectively return the hour in in the "12 hours" format. If you want it in the "24 hours" format you should use `HH`
