### ISSUE TITLE
import TYPE_CHECKING breaks python 3.5.0 and 3.5.1 compatibility

### ISSUE THREAD

**Issue by sfc-gh-mkeller** [sdispater/pendulum#473]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: CentOS 7
- **Pendulum version**: 2.1.0

## Issue

Hi,

The following line breaks compatibility for Python 3.5.0 and 3.5.1https://github.com/sdispater/pendulum/blob/c99f24215faf1fca544858a7a1ec6ff3538aa34f/pendulum/helpers.py#L11

Here's an official workaround if you'd want to fix this issue: https://mypy.readthedocs.io/en/stable/common_issues.html#import-cycles

Thanks for all your work, I just wanted to let you know!

**Comment by Secrus** [comment]
Won't be an issue in the next release.
