### ISSUE TITLE
DateTime.time() does not preserve tzinfo

### ISSUE THREAD

**Issue by BryceBeagle** [sdispater/pendulum#481]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Arch Linux
- **Pendulum version**: 2.1.0

## Issue

I would expect `tzinfo` to be maintained when converting from a `pendulum.DateTime` to a `pendulum.Time`, but it is not:

```python
>>> datetime = pendulum.datetime(2020, 6, 20, tz="UTC")
>>> print(datetime.tzinfo)
Timezone('UTC')
>>> print(datetime.time().tzinfo)
None
```

**Comment by sdispater** [comment]
This not the case in the standard library either and since Pendulum tries to be as close as possible this is expected.

```
>>> dt = datetime.now().astimezone()
>>> print(dt.tzinfo)
CEST
>>> print(dt.time().tzinfo)
None
```
