### ISSUE TITLE
test_construct.ConstructTest.test_now fails on systems with timezone set to anything equal to Europe/Paris

### ISSUE THREAD

**Issue by AndreasBackx** [sdispater/pendulum#49]
During my testing [`test_construct.ConstructTest.test_now`](https://github.com/sdispater/pendulum/blob/develop/tests/pendulum_tests/test_construct.py#L129) constantly failed. I assume it's because I have the same timezone that is being inputted and so the hour in Paris and my PC is gonna be the same. I haven't looked further in it during my work on #48.

**Comment by AndreasBackx** [comment]
Just tested it by setting my timezone on my Mac to London instead of Brussels and that does make all of the tests pass.

**Comment by sdispater** [comment]
That's strange. `LocalTimezone.get()` is mocked to always return the `America/Toronto` timezone so the test should pass.

**Comment by sdispater** [comment]
I just fixed it on `master`
