### ISSUE TITLE
Problem with poetry configuration

### ISSUE THREAD

**Issue by dekoza** [sdispater/pendulum#498]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Manjaro Linux, current (5.8.6-1-MANJARO)
- **Pendulum version**: master

## Issue

I'm trying to toy with an idea of new feature. I use Poetry on regular basis (currently 1.0.10) and when I try to do `poetry install` I get:

```
$ poetry install

[RuntimeError]
The Poetry configuration is invalid:
  - [build] {'generate-setup-file': <tomlkit.items.Bool object at 0x7f4fc7cc7df0>, 'script': 'build.py'} is not of type 'string'
```

I'm not sure if this a bug in Poetry, but I have no problems in other of my projects. I have not yet made any modifications to the codebase - just pulled latest master from this repo.

P.S.
I installed poetry using its official installer.

**Comment by dekoza** [comment]
OK, it actually need poetry 1.1.0b2. I think this should be mentioned somewhere :wink:

**Comment by GabrielSimonetto** [comment]
Thank you for your issue, I didn't know how to fix it.

**Comment by Secrus** [comment]
Since Pendulum now requires Poetry 1.2 for development, this issue is no longer relevant. That being said, a proper `CONTRIBUTING.md` file will be added to avoid such problems in the future.
