### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [sdispater/pendulum#517]
**Summary**
Installing pendulum on aarch64 via pip using command "pip3 install pendulum" tries to build wheel from source code.

**Problem description**
pendulum doesn't have wheel for aarch64 on PyPI repository. So, while installing pendulum via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pendulum. Making wheel available for aarch64 will benefit aarch64 users by minimizing pendulum installation time.

**Expected Output**
Pip should be able to download pendulum wheel from PyPI repository rather than building it from source code.

@pendulum-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pendulum wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by Secrus** [comment]
Pendulum 3.0 was released, along with wheels for aarch64
