### ISSUE TITLE
Fixing the build...  (drop 2.7 and 3.5 ?)

### ISSUE THREAD

**Issue by altendky** [sdispater/pendulum#550]
I submitted https://github.com/sdispater/pendulum/pull/548 and when the build failed I looked around and noticed that master was broken as well.  First off, a little black was needed.  Then an update to `install-poetry.py` from `get-poetry.py`.  But, that only supports 3.6+.  So...  where are we going with this?  I started a few changes in https://github.com/sdispater/pendulum/pull/549.

**Comment by hugovk** [comment]
Many projects have already dropped them, and especially when supporting them becomes a burden, sounds like a good time to drop them.

They're also little used.

Here's the pip installs for Pendulum from PyPI for May 2021:

| category | percent | downloads |
| -------- | ------: | --------: |
| 3.7      |  63.52% | 2,484,047 |
| 3.6      |  19.32% |   755,497 |
| 3.8      |  10.44% |   408,318 |
| 3.5      |   2.11% |    82,488 |
| null     |   1.63% |    63,852 |
| 3.9      |   1.55% |    60,592 |
| 2.7      |   1.42% |    55,472 |
| 3.10     |   0.00% |       112 |
| 3.4      |   0.00% |        63 |
| Total    |         | 3,910,441 |

Source: `pip install -U pypistats && pypistats python_minor pendulum --last-month`

**Comment by Secrus** [comment]
The next version is set to support python 3.7+. Closing.
