### ISSUE TITLE
UTC object in datetime timezones prevent instantiation

### ISSUE THREAD

**Issue by guyzmo** [sdispater/pendulum#56]
Using a lib I received a `datetime` object I wanted to convert to pendulum, so I did the following and it failed because of the `tzinfo` not being a string but an `UTC` instance:

``` python
>>> pendulum.instance(repo.updated_at)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/pendulum/pendulum.py", line 205, in instance
    tzinfo=tz
  File "…/pendulum/pendulum.py", line 180, in __init__
    self._tz = self._safe_create_datetime_zone(tzinfo)
  File "…/pendulum/pendulum.py", line 118, in _safe_create_datetime_zone
    tz = cls._timezone(obj)
  File "…/pendulum/pendulum.py", line 148, in _timezone
    return Timezone.load(zone)
  File "…/pendulum/tz/timezone.py", line 44, in load
    if name.upper() == 'UTC':
AttributeError: 'UTC' object has no attribute 'upper'
>>> repo.updated_at
datetime.datetime(2016, 10, 16, 10, 24, 5, tzinfo=UTC())
```

As a workaround I'm doing:

``` python
>>> pendulum.parse(repo.updated_at.isoformat())
<Pendulum [2016-10-16T10:24:05+00:00]>
>>>
```

but it sucks to be using a string as an intermediate format, when we could convert directly 😖

**Comment by sdispater** [comment]
That's strange because `instance()` should handle any tzinfo properly. Where does the `UTC()` comes from and is it a subclass of `tzinfo`?

**Comment by guyzmo** [comment]
it's coming from the `github3.py` library.

Exactly, the [`Repository.updated_at` member](http://github3py.readthedocs.io/en/master/repos.html?highlight=updated_at#github3.repos.repo.Repository.updated_at).

I believe it's being [built there](https://github.com/sigmavirus24/github3.py/blob/develop/github3/repos/repo.py#L168), which uses [that`_strptime()` method](https://github.com/sigmavirus24/github3.py/blob/develop/github3/models.py#L90,L104), which uses [an instance of that `UTC` class](https://github.com/sigmavirus24/github3.py/blob/develop/github3/utils.py#L48,L65).

So if it's all as it seems, yes it's a subclass of `tzinfo`! ☺

**Comment by guyzmo** [comment]
Here's a reproduceable example:

``` python
>>> import github3
>>> gh = github3.login(token="USE_A_PRIVATE_TOKEN_FROM_YOUR_GITHUB_SETTINGS")
>>> from datetime import tzinfo
>>> isinstance(list(gh.iter_user_repos('guyzmo'))[0].updated_at.tzinfo, tzinfo)
True
```

**Comment by sdispater** [comment]
You should update `pendulum` to the latest version (`0.6.2`). This bug has been fixed in `0.6.0` (552c34de70fe22606b7fdf34b8f45dc2c53a29cf)

**Comment by guyzmo** [comment]
oops! My bad and apologies ☺
I really thought I had it up to date, good thing that I did give the version number… As we say, "ça arrive même aux meilleurs" :stuck_out_tongue:

**Comment by guyzmo** [comment]
``` python
% pip install --upgrade pendulum
% python
>>> import github3, pendulum
>>> gh = github3.login(token='XXXXXXXX')
>>> pendulum.instance(list(gh.iter_user_repos('guyzmo'))[0].updated_at)
<Pendulum [2014-03-24T16:07:25+00:00]>
```

♥
