### ISSUE TITLE
cannot import DateTime from pendulum

### ISSUE THREAD

**Issue by jayanthiTinuiti** [sdispater/pendulum#572]
Traceback (most recent call last):
  File "/home/jayanthi/test.py", line 2, in <module>
    from pendulum import DateTime
ImportError: cannot import name 'DateTime' from 'pendulum' (/home/jayanthi/.local/lib/python3.9/site-packages/pendulum/__init__.py)

- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Ubunut 20.0.4
- **Pendulum version**:

**Comment by qiuyujx** [comment]
Could you try the follows?
```
from pendulum.datetime import DateTime
```

**Comment by jayanthiTinuiti** [comment]
Thanks, it worked out now.
