### ISSUE TITLE
Poetry configuration is invalid: `group`

### ISSUE THREAD

**Issue by za** [sdispater/pendulum#603]
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://pendulum.eustace.io/docs/) and believe that my question is not covered.

## Issue

I can't run `poetry install`. Is this issue with Pendulum or poetry version?

```
➜  pendulum git:(master) poetry install

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
➜  pendulum git:(master) poetry --version
Poetry version 1.1.13
```

**Comment by rileyjohngibbs** [comment]
I ran into this and fixed it based on [this comment](https://github.com/python-poetry/poetry/issues/4983#issuecomment-1055748382) pointing out that pendulum uses a preview version of poetry, so unless you specifically install that version, poetry won't work properly with pendulum's config.

So it's not so much a poetry issue as it is pendulum being a little eager to have those sweet new features. 😅

**Comment by za** [comment]
Hi @rileyjohngibbs thanks for the hint! It works now.

```
➜  pendulum git:(master) poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: pendulum (3.0.0a0)
```

And the poetry version now:
```
➜  pendulum git:(master) poetry --version
Poetry (version 1.2.0a2)
```
