### ISSUE TITLE
Type annotations of functions in datetime.py

### ISSUE THREAD

**Issue by SBolo** [sdispater/pendulum#622]
- [X] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://pendulum.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
Hi everyone,
is there a plan to add type annotations in the functions in datetime.py that still miss them? Currently, when using mypy some of the functions are impossible to use without a `type: ignore` (e.g. timestamp, set and many many others). I am willing to help out and prepare a PR myself about some of them, but I just wanted to make sure there is not anybody working on it already! Let me know :)

**Comment by Secrus** [comment]
Should be solved in the next release (and on the master branch).
