### ISSUE TITLE
"Why Not Arrow?" needs update

### ISSUE THREAD

**Issue by reagle** [sdispater/pendulum#624]
I was just looking at Arrow and Pendulum wondering which one to use and I ran through the examples; none of the responses attributed to Arrow are true.

**Comment by Secrus** [comment]
That section was removed.

**Comment by barraponto** [comment]
it was not removed, or if it was it is back: https://pendulum.eustace.io/faq/#why-not-arrow

**Comment by reagle** [comment]
The section in the FAQ is much more limited than the section on the homepage I was speaking of. Even so, some of the examples in the current FAQ fail (arrow and pendulum):

```
pendulum.parse('2016-1-17')
ParserError: Unable to parse string [2016-1-17]
```
