### ISSUE TITLE
Suggested method for YouTube duration (ISO8061) to seconds

### ISSUE THREAD

**Issue by PFython** [sdispater/pendulum#653]
- [x ] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://pendulum.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

YouTube uses ISO8061 (not to be confused with IS8601... which I did!).  It would be great to add a preset for converting YouTube durations to seconds which is a very common operation for anyone playing with YouTube programmatically.  Suggested basic function below:

```
import re

def yt_time(duration="P1W2DT6H21M32S"):
    """
    Converts YouTube duration (ISO 8061)
    into Seconds

    see http://en.wikipedia.org/wiki/ISO_8601#Durations
    """
    ISO_8601 = re.compile(
        'P'   # designates a period
        '(?:(?P<years>\d+)Y)?'   # years
        '(?:(?P<months>\d+)M)?'  # months
        '(?:(?P<weeks>\d+)W)?'   # weeks
        '(?:(?P<days>\d+)D)?'    # days
        '(?:T' # time part must begin with a T
        '(?:(?P<hours>\d+)H)?'   # hours
        '(?:(?P<minutes>\d+)M)?' # minutes
        '(?:(?P<seconds>\d+)S)?' # seconds
        ')?')   # end of time part
    # Convert regex matches into a short list of time units
    units = list(ISO_8601.match(duration).groups()[-3:])
    # Put list in ascending order & remove 'None' types
    units = list(reversed([int(x) if x != None else 0 for x in units]))
    # Do the maths
    return sum([x*60**units.index(x) for x in units])
```

**Comment by Gamrix** [comment]
searching for ISO 8061 only pulls up Alpine Ski Binding regulations (and tons of links for 8601) , and not time formats. Can you provide more links to this time format documentation. 
https://www.iso.org/search.html?q=8061

**Comment by PFython** [comment]
Apologies typo - it should indeed by ISO8601.

Not to down-play the obvious importance of Alpine Ski Binding regulations to your repository (!) but here's the standard I meant to reference, used for YouTube durations amongst other things:

http://en.wikipedia.org/wiki/ISO_8601#Durations

All the best,
Pete

**Comment by Gamrix** [comment]
Ok, now that we know that it is ISO 8601, I went in and checked if Pendulum supports this, and it actually does. See the following snippet. 

```
>>> import pendulum
>>> d = pendulum.parse("P3Y6M4DT12H30M5S")
>>> d
Duration(years=3, months=6, days=4, hours=12, minutes=30, seconds=5)
>>> d.total_seconds()
110550605.0
```

**Comment by PFython** [comment]
Great to know thank you so much!
