### ISSUE TITLE
pendulum.instance shifts UTC value by one hour during DST transition ambiguous hour

### ISSUE THREAD

**Issue by martin-schulze-e2m** [sdispater/pendulum#658]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 22.04
- **Pendulum version**: 2.1.2

## Issue

Have a look at this annotated REPL session and note the difference in UTC offsets but not hour (or timestamps respectively):

```
>>> time = datetime.datetime.fromisoformat("2022-10-30 02:00+02:00").astimezone(pendulum.timezone("CET"))
>>> str(time)
'2022-10-30 02:00:00+02:00'
>>> str(pendulum.instance(time))
'2022-10-30T02:00:00+01:00' # hour remains the same but UTC offset changes?
>>> time.timestamp()
1667088000.0
>>> pendulum.instance(time).timestamp()
1667091600.0 # clearly another time!
```

As you can see, the `pendulum.instance` shifted in time by one hour. The peculiar setup code for `time` mimicks the behavior we see with a SqlAlchemy ORM which reads values in UTC+x format from DB, which are then required in the given timezone to account for DST effects.

While a change in UTC offset might be understandable, e.g. '2022-10-30T01:00:00+01:00' (note the hour changing as well), I would expect `pendulum.instance` to retain the same UTC timestamp.

**Comment by martin-schulze-e2m** [comment]
The problem also happens with `time.astimezone(pendulum.timezone("CET")`.

**Comment by sdispater** [comment]
This is fixed in the `master` branch.
