### ISSUE TITLE
"timezone" is not exported from module "pendulum"

### ISSUE THREAD

**Issue by lmartinez-clgx** [sdispater/pendulum#664]
- [ ] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

**Comment by tekumara** [comment]
Also:
```
"DateTime" is not exported from module "pendulum"
  Import from "pendulum.datetime" instead
```

Exporting from `pendulum.datetime` works, but not the top level.

**Comment by tekumara** [comment]
Related to https://github.com/sdispater/pendulum/issues/595

**Comment by tokarser** [comment]
stop

**Comment by Secrus** [comment]
This is now exported properly and should be fine in the next release.
