### ISSUE TITLE
Unable to build wheel using pypa/build (PEP517)

### ISSUE THREAD

**Issue by dvzrv** [sdispater/pendulum#665]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Arch Linux
- **Pendulum version**: 2.1.1 and also https://github.com/sdispater/pendulum/commit/d902a46e369859890fd8464ecf3908d94361606f

## Issue
Hi! I maintain pendulum as a package for Arch Linux.
I am currently trying to use [pypa/build](https://github.com/pypa/build) to build wheels for this project, but build does not create a wheel (see https://github.com/pypa/build/issues/526).
I am not entirely sure whether this is an issue with pypa/build, pendulum or poetry, but with PEP517 it should be possible to build wheels of a project using pypa/build and the respective build-system requirements of a project (in this case poetry-core, meson and ninja - at 2.1.1 only poetry-core).

As background info: For bootstrapping Python for the upcoming 3.11.0 update we want to keep the bootstrapping to a minimum if possible and only provide the packages we *actually* need to build the others (in this case build, installer, poetry-core, wheel).

**Comment by sdispater** [comment]
The issue comes from the fact that when you execute `python -m build`, it will execute the `build.py` script directly since the current directory has precedence in `sys.path`.

You can try to use `pyproject-build --wheel` instead.

**Comment by dvzrv** [comment]
Argh.... :facepalm: 

Thanks for pointing out the obvious. That has of course been the problem!

Hm, to circumvent name clashes, maybe the script could be renamed to something more specific in the future? E.g. `build_extensions.py` or so?

**Comment by henryiii** [comment]
I'd recommend `pipx run build`, personally. :)

**Comment by dvzrv** [comment]
> I'd recommend pipx run build, personally. :)

Hm, that would not help in system's packaging, though. We do not want to bundle everything for every package of course :)
Apart from increasing the required disk space for each package, pipx would have to be bootstrapped on new versions of python (e.g. 3.11). It's not really suitable for this kind of task unfortunately.
