### ISSUE TITLE
Interval: allow comparing of Pendulum() and Period() objects

### ISSUE THREAD

**Issue by flokli** [sdispater/pendulum#67]
After having defined `p1` (from now until tomorrow):
```python
>>> now = pendulum.utcnow()
>>> p1 = pendulum.Period(utcnow, now.tomorrow())
```
I can ask whether a specific `Pendulum` object is inside `p1`:
```python
>>> now.add(hours=1) in p1
True
>>> now.yesterday() in p1
False
```
But when a `Pendulum` object is outside a given `Period`, I can't ask whether its before or after the `Period`:
```python
>>> now.yesterday() < p1
TypeError: unorderable types: Pendulum() < Period()
```

Of course, I could compare `p1.start` and `p1.end`, but this would make it more convenient.

**Comment by sdispater** [comment]
I agree.

I will target this change for the `0.7` version.

**Comment by flokli** [comment]
Thanks!

**Comment by sdispater** [comment]
After thinking about it a little more, I think I will hold off on that. I think it will create confusion since you will only be able to compare using `<` and `>` but not `>=`, `<=` and `==` (a Pendulum instance can't be equal to a Period).

So i am more inclined to enforce explicit comparison by using the `period.start` and `period.end`.

**Comment by flokli** [comment]
I'd be fine with only being able to compare via `>` and `>`, but not via `<=` and `>=`, if doing the latter raises an exception that described that you wanted to compare things that don't make any sense.

I normally name variables which are easy to recognize if they are `Period` or a `datetime`/`Pendulum` objects, so it's pretty obvious what I compare with what.
In my case, I often compare datetimes with Periods, and would have loved to save some keystrokes /boilerplate while doing this.
However, if you want to enforce explicit comparison, I can also arrange with that.
