### ISSUE TITLE
Windows Installation 

### ISSUE THREAD

**Issue by adityakumar1990** [sdispater/pendulum#682]
While installing it on windows I am getting below error 
Tried using different version of poetry & pendulum but still facing issue .
  ERROR: Failed building wheel for orjson
  Running setup.py clean for orjson
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\USER\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER
\\AppData\\Local\\Temp\\pip-install-28_n3c1e\\orjson\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-28_n3c1e\\orjson\\setup.p
y'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'
"'))' clean --all
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-28_n3c1e\orjson
  Complete output (3 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'setuptools'
  ----------------------------------------
  ERROR: Failed cleaning build dir for orjson
Failed to build cryptography orjson
ERROR: Could not build wheels for cryptography, orjson which use PEP 517 and cannot be installed directly

**Comment by Secrus** [comment]
Seems like a problem with your Python installation. There are no wheels of orjson for 32-bit windows. Not a Pendulum issue.
