### ISSUE TITLE
Adapt with Django

### ISSUE THREAD

**Issue by ieiayaobb** [sdispater/pendulum#69]
As Django need a datetime object to be stored into a DateTimeField, I'm using '__getattribute__('datetime')' to get the datetime object now, any better solutions?

**Comment by AndreasBackx** [comment]
There is `Pendulum._datetime` you could use, but it's not really documented and it's a private field. I was gonna look into using Pendulum objects directly, but I'm currently busy too. @sdispater probably knows more.

**Comment by sdispater** [comment]
That's strange. The `Pendulum` class is a subclass of `datetime` so there should not be any problem for it to work with `DateTimeField`.

**Comment by AndreasBackx** [comment]
@sdispater now that I test it. It does seem to work. I remembered coming across a small problem once. Well no matter now I guess.

**Comment by ieiayaobb** [comment]
Well, I tried to save directly with `Pendulum` object into a `DateTimeField`. 
It said`AttributeError: 'UTC' object has no attribute 'upper'`.

I saw the source code of `timezone.py` line 43
`if name.upper() == 'UTC'`
In this context, `name`'s type is `django.utils.timezone.UTC`, not a `string`. So it can't call the `upper` method.

**Comment by sdispater** [comment]
@ieiayaobb Which version of `pendulum` are you using?

**Comment by ieiayaobb** [comment]
I've changed the version to the latest(0.6.5), and problem solved.
it seems get another trouble.
When I use `pendulum.utcnow()` to store, it can be saved successfully, but when I try to get it, `ValueError: Not naive datetime (tzinfo is already set)` will occur. 
Then I checked the data stored in MySQL, something is different between `django.utils.timezone.now()`'s value.

 - `django.utils.timezone.now()` = `2016-11-04 04:35:32.872716`
 - `pendulum.utcnow()` = `2016-11-04T05:00:56.391080+00:00`
 - `pendulum.utcnow().to_datetime_string()` = `2016-11-03 20:42:52`

The 1st and 3rd solution can be used without any issue, 
but the 3rd is not correct due to the timezone info.

How can I use it in a correct way?

**Comment by sdispater** [comment]
`django` will use the `isoformat()` method to store datetimes in the database. However since `pendulum` is always timezone aware there is no way to remove the offset information from `isoformat()`.

However, there are ways to work around the issue:

- Register a converter for MySQLdb to make it properly convert `Pendulum` instances.

```python
# Fix for understanding Pendulum object
import MySQLdb.converters
from pendulum import Pendulum

MySQLdb.converters.conversions[Pendulum] = MySQLdb.converters.DateTime2literal
```

That's what is used in [Orator](https://github.com/sdispater/orator) for the [MySQL connector](https://github.com/sdispater/orator/blob/master/orator/connectors/mysql_connector.py#L11).

- Create a new field type inheriting from `DateTimeField` like so:

```python
from django.db.models import DateTimeField as BaseDateTimeField
from pendulum import Pendulum


class DateTimeField(BaseDateTimeField):

    def value_to_string(self, obj):
        val = self.value_from_object(obj)

        if isinstance(value, Pendulum):
            return value.to_datetime_string()        

        return '' if val is None else val.isoformat()
```

Note that, I haven't tested the second solution myself.

**Comment by ieiayaobb** [comment]
@sdispater Cool, I will use as you suggested, thank you very much.

**Comment by ulope** [comment]
IMO this issue should be reopened. Just because it's possible to "hack" your way around this problem doesn't mean that it doesn't exist anymore. 

At least I'd suggest that a section about compatibility with libraries expecting "standard" datetime objects should be added to the docs.

**Comment by sdispater** [comment]
@ulope It's just that there is no way to fix it on pendulum's end. Django expects a naive datetime while Pendulum instances are always aware so there is not much to do about it.

I agree that I could add a "limitations" section in the README and in the documentation to list the cases where replacing datetime instances by pendulum instances does not work properly and, if any, provide a solution or workaround for these cases.
