### ISSUE TITLE
[mypy] Explicit re-export

### ISSUE THREAD

**Issue by AdrienPensart** [sdispater/pendulum#695]
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://pendulum.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Hello / Salut!

I have two minor issues when using static typing tool : 

error: "Module pendulum" does not explicitly export attribute "timezone"  [attr-defined]
            canada = pendulum.timezone("America/Toronto")
                     ^~~~~~~~~~~~~~~~~
error: Name "pendulum.Period" is not defined  [name-defined]
            delta: pendulum.Period = time_spent[1] - time_spent[0]
                   ^

Is is possible to explicitely re-export all needed / most-used symbols in pendulum/__init__.py ?

Thank you!

**Comment by bryanforbes** [comment]
I believe this has been addressed in #680

**Comment by sdebruyn** [comment]
> I believe this has been addressed in #680

I don't think so. You'd need to put something like

```python
__all__ = [
    "Period",
]
```

in `__init__.py` in the pendulum package

**Comment by Secrus** [comment]
Should be fine now. Notice that in Pendulum 3.0 `Period` is renamed to `Interval`.
