### ISSUE TITLE
provide wheel for python3.11-windows

### ISSUE THREAD

**Issue by rodrigosge20** [sdispater/pendulum#709]
provide wheel for python3.11-windows, currently the latest windows wheel found in PyPI is for python3.9

**Comment by edgarrmondragon** [comment]
There are Windows wheels in the current 3.0.0b1 pre-release if you want to give them a try: https://pypi.org/project/pendulum/3.0.0b1/#files

**Comment by Secrus** [comment]
Pendulum 3.0 was released, with wheels for 3.11-windows
