### ISSUE TITLE
differentiate between locales en-us and en-gb

### ISSUE THREAD

**Issue by georgpfolz** [sdispater/pendulum#724]
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://pendulum.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I love the localized formats! But the English outputs for **en** are US-American formats (concerning the order of day and month). It would be great to be able to specify **en-gb** to get more European results:

```
now = pendulum.now()
now.format('LLLL', locale='en')  → Thursday, September 4 1986 8:30 PM
now.format('LLLL', locale='en-us')  → Thursday, September 4 1986 8:30 PM
now.format('LLLL', locale='en-gb') → Thursday, 4 September 1986 8:30 PM
```

What I also miss is a localized format token that returns just the day and the month (maybe `LL-`?), so that it's easily combined with other tokens in a format string:

```
now.format('LL-', locale='en-gb') → 4 September
now.format('LL-', locale='en-us') → September 4
now.format('dddd, LL- LT', locale='en-gb') → Thursday, 4 September 8:30 PM
```

**Comment by Secrus** [comment]
Done in #731
