### ISSUE TITLE
Pendulum issues with new timezones

### ISSUE THREAD

**Issue by adam006** [sdispater/pendulum#743]
- [x] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Mac OS 13.3.1 (22E261)
- **Pendulum version**: 2.1.2

## Issue

We are running into issues with pendulum using new timezones. For instance when using the new timezone "America/Ciudad_Juarez" we receive the following message -
`pendulum.tz.zoneinfo.exceptions.InvalidTimezone: Invalid timezone "America/Ciudad_Juarez"`. Is there a way we can update what pendulum is using for timezone data? The native datetime and zoneinfo do not have any issue finding this new timezone.

**Comment by edgarrmondragon** [comment]
Have you tried one of the approaches in https://github.com/sdispater/pendulum/issues/700?

For example, I've used https://github.com/sdispater/pendulum/issues/700#issuecomment-1504440674:

```python
import pendulum
import pytzdata

print(pendulum.__version__)  # 2.1.2

pytzdata.set_directory("/usr/share/zoneinfo")

dt_juarez = pendulum.datetime(2020, 1, 1, tz="America/Ciudad_Juarez")
print(dt_juarez)  # 2020-01-01T00:00:00-07:00
```

**Comment by adam006** [comment]
looks like that takes care of it! thank you very much for the direction!
