### ISSUE TITLE
time for a release? 

### ISSUE THREAD

**Issue by kapilt** [sdispater/pendulum#744]
per GitHub v2 last release was over 3 years ago. v3 alpha last release is almost a year old. anything community can do to help?

**Comment by radkujawa** [comment]
I think [this](https://github.com/sdispater/pendulum/issues/600) is the ticket on new releases. I wrote 3 weeks ago a post there, but I got no reaction unfortunately :(

**Comment by Secrus** [comment]
Closing as duplicate of #600
