### ISSUE TITLE
How to install Pendulum without PIP

### ISSUE THREAD

**Issue by thecalle** [sdispater/pendulum#746]
- [X] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://pendulum.eustace.io/docs/) and believe that my question is not covered.

## Issue

Building Docker image without PIP (Debian:XXX.slim) **reduces the size of image** by half.

Is it possible to install Pendulum package with python3 setup.py install procedure without using PIP install?

Normally I omit python3-pip install to avoid a lot of packages will be installed and grow the image size.

Thanks in advance.

**Comment by Secrus** [comment]
We only support installation via PEP 517 API (so pip and other compatible apps). The only thing I can think of is to make project venv in another build stage and then copy that venv into the production container.
