### ISSUE TITLE
Consider releasing Pendulum 3 or 2.1.2 with patches

### ISSUE THREAD

**Issue by bolkedebruin** [sdispater/pendulum#753]
Hi!

I am one of the Apache Airflow maintainers. Apache Airflow is heavily reliant on Pendulum for its timezone support and we are very grateful for the service that it provides. However, with the latest release of Pendulum stemming from July 2020 we are seeing that issues, like [1], are starting to pop up due to stale timezone data. Being correct was always one of the strengths of Pendulum. Unfortunately, at this moment it is not anymore.

We understand that maintaining a project like this can take a significant amount of time. We see that an alpha has been releases of Pendulum 3, but cannot judge how far off a full release is. Should we start testing Pendulum 3 as part of our code base? Or, considering, our main pain point at this moment is outdated timezone information (there are other nits), is it smarter to backport support for system provided zoneinfo as in this commit [1] or potentially like [2] into Pendulum 2?

So how can we help? 

[1] https://github.com/apache/airflow/pull/30467
[2] https://github.com/sdispater/pendulum/commit/ae2c9f59beface872ec54c30b943a0bc3ad77273
[3] https://github.com/sdispater/pendulum/issues/706

@sdispater @Secrus

**Comment by Secrus** [comment]
Hi. We are working on 3.0 release. See https://github.com/sdispater/pendulum/issues/600#issuecomment-1711299677 for more details. We do not plan to release any more 2.x versions AFAIK.

**Comment by bolkedebruin** [comment]
I understand you are working on it, the question is can we help in anyway to speed things up? The last alpha release was from November 2022, so I assume significant changes have been made in the meantime.

**Comment by mattsta** [comment]
We're in the same boat here.

We switched a dozen internal services from arrow to Pendulum in 2021, but now we're stuck not being able to upgrade to Python 3.12 because Pendulum 2.x isn't happy unless we upgrade with `--pre`.


3.12.0 build failure output with the current pypi release:

```haskell
Collecting pendulum
  Downloading pendulum-2.1.2.tar.gz (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 6.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytzdata>=2020.1 (from pendulum)
  Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.0/490.0 kB 23.1 MB/s eta 0:00:00
Building wheels for collected packages: pendulum
  Building wheel for pendulum (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pendulum (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/sk/zncv9ddn375grsn9fddr0hj00000gn/T/pip-install-dvqbja46/pendulum_bb6d1c36847d4ef9887f7927387d1b8f/build.py", line 5, in <module>
          from distutils.command.build_ext import build_ext
      ModuleNotFoundError: No module named 'distutils'
    
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pendulum
Failed to build pendulum
ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects
```

**Comment by Secrus** [comment]
Pendulum 3.0 was released.
