### ISSUE TITLE
Adding Interval to Pendulum produces incorrect results

### ISSUE THREAD

**Issue by ulope** [sdispater/pendulum#77]
```
from pendulum import Pendulum, Interval

p = Pendulum.now()
p2 = p + Interval(minutes=15)
assert p == p2
```

The reason is that `Pendulum.add_timedelta()` assumes a default python `timedelta` object and can't cope with the non-normalizing behavior of `Interval`.

**Comment by sdispater** [comment]
The internals of Interval have been changed and fixed in the `develop` branch.

```python
>>> import pendulum
>>> p = pendulum.now()
>>> p2 = p + pendulum.interval(minutes=15)
>>> p == p2
False
```

This fix will land in the next `0.7.0` release.
