### ISSUE TITLE
backports-zoneinfo does not compile on 3.10, and hard to package (pyinstaller, zipapp,...)

### ISSUE THREAD

**Issue by gsemet** [sdispater/pendulum#796]
Can you remove the dependency on backports-zoneinfo, or make it optional ? It is hard to package into a shiv executable (zipapp) that will run on python 3.9 and 3.10, because this (ugly) package does not compile on 3.10 (instead of just doing nothing silently.

Thanks

**Comment by gsemet** [comment]
Have tried to use pendulum in a shiv (zipapp)? It basically create a single package for several version of python (usually) so there is no way to provide the marker pip can use.

**Comment by Secrus** [comment]
I suggest you take it to `shiv` authors. PEP 508 markers are a proper way to use conditional dependencies and should be respected by installers of any kind
