### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by brunns** [sdispater/pendulum#80]
If I run the following:

```python
import pendulum

while True:
    pendulum.now()
```

It will consume more and more memory until the interpreter dies. (The same does not happen with ```datetime.datetime.now()```.)

**Comment by ntoll** [comment]
Hi.... I'm a colleague of @brunns 

See this: https://github.com/sdispater/pendulum/blob/master/pendulum/_extensions/_helpers.c..?

Now see this:
```
from pendulum._extensions._helpers import local_time

while True:
    local_time(0,0)
```

Now watch the memory grow... :-/

**Comment by sdispater** [comment]
Nice catch!

I will merge you PR and release a bugfix version.

**Comment by sdispater** [comment]
Version `0.6.6` has just been released.
