### ISSUE TITLE
Either .minutes or .seconds is inconsistent when subtracting one datetime from another.

### ISSUE THREAD

**Issue by cardboardpig** [sdispater/pendulum#85]
```
In [1]: import pendulum

In [2]: start = pendulum.parse('2016-10-27 9:00')

In [3]: end = pendulum.parse('2016-10-27 10:01:30')

In [4]: period = end - start

In [5]: period.hours
Out[5]: 1

In [6]: period.minutes
Out[6]: 1

In [7]: period.seconds
Out[7]: 3690
```

I would have thought .seconds would return 30? Or perhaps minutes should return 61 (or 61.5)?

**Comment by sdispater** [comment]
This is due to the fact that pendulum keeps the compatibility with the standard `timedelta` class where `.seconds` return the total number of seconds of the timedelta. If you want the remaining seconds you can use the `.remaining_seconds` property.
