### ISSUE TITLE
 Pendulum (2.1.0) to (2.1.2) not supporting PEP 517 builds

### ISSUE THREAD

**Issue by SSD1805** [sdispater/pendulum#862]
- [ ] I am on the [latest](https://github.com/sdispater/pendulum/releases/latest) Pendulum version.
- [x] I have searched the [issues](https://github.com/sdispater/pendulum/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 11 Pro (Version 22H2)
- **Pendulum version**: 2.1.1 (also tested with 2.1.0 and 2.1.2)

## Issue

When attempting to install Pendulum (versions 2.1.0, 2.1.1, and 2.1.2) using Poetry with Python 3.12, the installation fails due to a missing `distutils` module. It seems that Pendulum's build script (`build.py`) relies on `distutils`, which has been removed from Python 3.12 as of [PEP 632](https://peps.python.org/pep-0632/).

### Additional Notes:
1. I initially tried using Python 3.13 but switched to Python 3.12 due to similar issues. The problem persists.
2. I also tested with Python 3.11, but the installation error still occurred.
3. I attempted the installation using two different shells: **fish shell** and **PowerShell**, with the same results.

### Error Traceback:
```plaintext
Traceback (most recent call last):
  File "/tmp/tmp19tda2f0/pendulum-2.1.1/build.py", line 4, in <module>
    from distutils.command.build_ext import build_ext
ModuleNotFoundError: No module named 'distutils'
```

### Steps to Reproduce:
1. Install Python 3.12.
2. Set up a virtual environment using Poetry.
3. Add Pendulum as a dependency in `pyproject.toml` (e.g., `pendulum = "^2.1.1"`).
4. Run `poetry install`.

### Expected Behavior:
Pendulum should install without errors.

### Actual Behavior:
Installation fails because `distutils` is not present in Python 3.12.

---

### Proposed Solution:
Update Pendulum's build process to eliminate its dependency on `distutils`. Modern alternatives such as `setuptools` or `wheel` can be used instead.

---

If you need further details or assistance reproducing the issue, please let me know. Thank you! 🙌❤️

**Comment by Secrus** [comment]
We don't support 2.x series anymore. You should migrate to 3.0.
