### ISSUE TITLE
Allow use of alternative formatter with f-strings

### ISSUE THREAD

**Issue by rkhwaja** [sdispater/pendulum#90]
>>> pendulum.set_formatter("alternative")
>>> f"{pendulum.now():YYYY}"
'YYYY'

Should return 2017

**Comment by sdispater** [comment]
Yes, right now it only works with the `strftime` notation ('%Y' for example) regardless of the configured formatter.

I hadn't thought of this use case when I introduced the alternative formatter.

It will most likely be changed in version `1.1`
