### ISSUE TITLE
next and previous methods removes time informations

### ISSUE THREAD

**Issue by asrenzo** [sdispater/pendulum#92]
Hello,

Sounds like previous and next methods remove time informations from results.

```python
>>> import pendulum

>>> dt = pendulum.create(2017, 1, 30, 12)
>>> dt
<Pendulum [2017-01-30T12:00:00+00:00]>

>>> previous_dt = dt.previous(pendulum.SUNDAY)
>>> previous_dt
<Pendulum [2017-01-29T00:00:00+00:00]>

>>> dt          
<Pendulum [2017-01-30T12:00:00+00:00]>

>>> next_dt = dt.next(pendulum.TUESDAY)
>>> next_dt
<Pendulum [2017-01-31T00:00:00+00:00]>

>>> dt
<Pendulum [2017-01-30T12:00:00+00:00]>
```
Is this on purpose or an issue ?

Regards,

Laurent

**Comment by asrenzo** [comment]
I've seen this comes from the use of start_of in the next or previous methods but I this prevent from finding the next or previous day at the same time. For recurrent events this is not really convinient.

**Comment by sdispater** [comment]
Yes, this is on purpose.

As a workaround, you can do:

```python
>>> import pendulum

>>> dt = pendulum.create(2017, 1, 30, 12)
>>> next_dt = dt.next(pendulum.TUESDAY).at(dt.hour, dt.minute, dt.second)
```

However, I agree it's not that intuitive. Maybe adding a keyword argument to retain the time information (defaulting to `False` to keep the current behavior and not break the API) is the solution?

I will think about it.
