### ISSUE TITLE
Pendlum.parse doesn't match pendlum.parse

### ISSUE THREAD

**Issue by DanCardin** [sdispater/pendulum#95]
so normally, `pendlum.parse` would accept a string like `'2016-01-01'`, but `pendulum.Pendulum.parse('2016-01-01')` doesn't because it expects the `offset` key to exist in the resultant parsed dict.

**Edit:** Err so after reading the code tad more, its due to the `strict` parameter.  According to the docs, I was assuming that `strict` would just mean that a date string would return a date instead of a datetime. but it also keeps `normalize` from adding the offset key in the parsed dict.

but that doesnt make sense. so pretend i didnt open this issue!

**Comment by sdispater** [comment]
Yes, `strict` should only be used for `pendulum.parse()` and not `pendulum.Pendulum.parse()`.
