### ISSUE TITLE
Document tz param of pendulum.parse()

### ISSUE THREAD

**Issue by sametmax** [sdispater/pendulum#96]
While pendulum.from_format does the job fine, the convenience from pendulum.parse() is greater. The later, however, doesn't let you specify a timezone in the case the provided string doesn't contain one.

**Comment by sdispater** [comment]
This is not specified in the documentation (I will fix it) but you can pass a `tz` keyword argument to `parse()`:

```python
>>> import pendulum

>>> pendulum.parse('2017-03-03 12:34:56', tz='Europe/Paris')
# <Pendulum [2017-03-03T12:34:56+01:00]>
```

**Comment by sametmax** [comment]
All right, i'll change the title then :)

**Comment by sametmax** [comment]
Done. Cheers.

**Comment by sdispater** [comment]
The documentation has been updated.

**Comment by sametmax** [comment]
I just tested it and you are absolutely right.

**Comment by sametmax** [comment]
Woops, wrong bug. Thanks for the fix though.
