### ISSUE TITLE
Expose ParserError exception to top level imports

### ISSUE THREAD

**Issue by johnpneumann** [sdispater/pendulum#98]
Currently if you want to catch the `ParserError` when calling `pendulum.parse('string')`, you have to catch it with:

```
try:
  pendulum.parse('string')
except pendulum.parsing.exceptions.ParserError:
  pass
```

unless you've explicitly imported that part of the module in. There is already a `pendulum.exceptions`, so is there any reason why the `ParserError` couldn't be put into that same module or imported into the base init? I can make the PR for it, I just wanted to get clarity around whether this was by design or if it was something that wasn't a use case. I don't want to catch `ValueError`, mostly because that's not the exception being thrown.

**Comment by sdispater** [comment]
The idea behind it was that `pendulum.parsing` would be like a standalone package so the exceptions relative to parsing would be there.

However, I agree that we could import the `ParserError` exception in `pendulum.exceptions`.

**Comment by johnpneumann** [comment]
Awesome and thank you. I made a PR for this, though it's failing a test right now. I'll take a look at it to see why that change would have affected anything.

**Comment by sdispater** [comment]
From the look of it, I don't think the failing test is due to your PR. I seems more like a race condition.

**Comment by sdispater** [comment]
Test have been fixed!

**Comment by johnpneumann** [comment]
Awesome! Thank you!
